load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")
load("//build/rules/controller_gen:aspect.bzl", "kubebuilder_analyze")
load("//build/rules/controller_gen:kubebuilder.bzl", "api_package")

# gazelle:exclude zz_generated.*.go

kubebuilder_analyze(
    name = "v1_typedata",
    srcs = [
        "annotation_consts.go",
        "backend_type.go",
        "backendendpointhealthset_type.go",
        "backendservice_type.go",
        "backendservicepolicy_type.go",
        "cloudnatgateway_type.go",
        "cloudnatmapping_type.go",
        "doc.go",
        "flowgenerator_types.go",
        "flowlog_types.go",
        "forwardingruleexternal_type.go",
        "forwardingruleinternal_type.go",
        "groupversion_info.go",
        "healthcheck_type.go",
        "label_consts.go",
        "network_types.go",
        "organizationnetworkpolicy_types.go",
        "peergateway_types.go",
        "projectnetworkpolicy_types.go",
        "selector.go",
        "vpnbgppeer_types.go",
        "vpngateway_types.go",
        "vpntunnel_types.go",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/apis/core/v1alpha1",
        "//pkg/apis/public",
        "//pkg/apis/public/ipam/v1:ipam",
        "//pkg/apis/public/resourcemanager/v1alpha1",
        "//vendor/k8s.io/api/core/v1:core",
        "//vendor/k8s.io/api/networking/v1:networking",
        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
        "//vendor/k8s.io/apimachinery/pkg/runtime/schema",
        "//vendor/k8s.io/apimachinery/pkg/types",
        "//vendor/k8s.io/apimachinery/pkg/util/intstr",
        "//vendor/sigs.k8s.io/controller-runtime/pkg/scheme",
    ],
)

api_package(
    name = "v1_api",
    targets = [":v1_typedata"],
    visibility = ["//visibility:public"],
)

go_library(
    name = "networking",
    srcs = [
        "annotation_consts.go",
        "backend_type.go",
        "backendendpointhealthset_type.go",
        "backendservice_type.go",
        "backendservicepolicy_type.go",
        "cloudnatgateway_type.go",
        "cloudnatmapping_type.go",
        "condition_consts.go",
        "doc.go",
        "flowgenerator_types.go",
        "flowlog_types.go",
        "forwardingruleexternal_type.go",
        "forwardingruleinternal_type.go",
        "groupversion_info.go",
        "healthcheck_type.go",
        "label_consts.go",
        "network_types.go",
        "organizationnetworkpolicy_types.go",
        "peergateway_types.go",
        "pnp_validation.go",
        "projectnetworkpolicy_types.go",
        "selector.go",
        "vpnbgppeer_types.go",
        "vpngateway_types.go",
        "vpntunnel_types.go",
        "zz_generated.deepcopy.go",  # keep
    ],
    importpath = "github.com/googlecloudplatform/google-distributed-cloud-apis/pkg/apis/public/networking/v1",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/apis/core/v1alpha1",
        "//pkg/apis/public",
        "//pkg/apis/public/resourcemanager/v1alpha1",
        "//vendor/k8s.io/api/core/v1:core",
        "//vendor/k8s.io/api/networking/v1:networking",
        "//vendor/k8s.io/apimachinery/pkg/api/errors",
        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
        "//vendor/k8s.io/apimachinery/pkg/runtime",  # keep
        "//vendor/k8s.io/apimachinery/pkg/runtime/schema",
        "//vendor/k8s.io/apimachinery/pkg/util/intstr",
        "//vendor/k8s.io/apimachinery/pkg/util/validation/field",
        "//vendor/sigs.k8s.io/controller-runtime/pkg/scheme",
    ],
)

go_test(
    name = "networking_test",
    timeout = "moderate",
    srcs = ["pnp_validation_test.go"],
    embed = [":networking"],
    deps = [
        "//vendor/k8s.io/api/core/v1:core",
        "//vendor/k8s.io/api/networking/v1:networking",
        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
        "//vendor/k8s.io/apimachinery/pkg/util/intstr",
        "//vendor/k8s.io/utils/ptr",
    ],
)
