load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")
load("//build/rules/controller_gen:aspect.bzl", "kubebuilder_analyze")
load("//build/rules/controller_gen:kubebuilder.bzl", "api_package")

# gazelle:exclude zz_generated.*.go
# gazelle:exclude managedkeycloak_types_test.go

kubebuilder_analyze(
    name = "v2_typedata",
    srcs = [
        "doc.go",
        "groupversion_info.go",
        "managedkeycloak_types.go",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/apis/core/v1alpha1",
        "//pkg/apis/public",
        "//vendor/k8s.io/api/core/v1:core",
        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
        "//vendor/k8s.io/apimachinery/pkg/runtime/schema",
        "//vendor/sigs.k8s.io/controller-runtime/pkg/scheme",
    ],
)

api_package(
    name = "v2_api",
    targets = [":v2_typedata"],
)

go_library(
    name = "v2",
    srcs = [
        "condition_consts.go",
        "doc.go",
        "generated.deepcopy.go",  # keep
        "groupversion_info.go",
        "managedkeycloak_types.go",
    ],
    importpath = "gke-internal.googlesource.com/private-cloud/pkg/apis/public/keycloak/v2",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/apis/core/v1alpha1",
        "//pkg/apis/public",
        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
        "//vendor/k8s.io/apimachinery/pkg/runtime",  # keep
        "//vendor/k8s.io/apimachinery/pkg/runtime/schema",
        "//vendor/sigs.k8s.io/controller-runtime/pkg/scheme",
    ],
)

go_test(
    name = "v2_test",
    srcs = ["managedkeycloak_types_test.go"],
    embed = [":v2"],
    deps = [
        "//pkg/apis/core/v1alpha1",
        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
    ],
)
