// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Condition defines a condition for a filter.
type Condition struct {
	// +kubebuilder:validation:Required
	Path string `json:"path"` // JSON path (e.g., $.userAgent)
	// +kubebuilder:validation:Required
	Match string `json:"match"` // Regex or literal match
}

// Filter defines a rule for removing or replacing specific fields from audit logs. It can be used to filter sensitive information or any field irrelevant to the audit log.
type Filter struct {
	Name string `json:"name,omitempty"` // name of the filter for easy reference
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Enum=drop;redact
	Action     string      `json:"action"`               // "drop", "redact"
	TargetPath string      `json:"targetPath,omitempty"` // required for replace
	Conditions []Condition `json:"conditions,omitempty"` // All conditions must match
}

type ApiServerEntry struct {
	// +kubebuilder:validation:Required
	ResourceKind string `json:"resourceKind"` // kind of the resource definition e.g. virtualmachines.vm.cluster.gke.io
	// +kubebuilder:validation:Required
	AuditRelevant bool `json:"auditRelevant"` // true if there should be audit log collected for this resource
	// +kubebuilder:validation:Required
	Comment string `json:"comment"` // a comment for easy readability by a person

	ResourceName string   `json:"resourceName,omitempty"` // If omitted, applies to all if set this configuration only applies if this is set as name especially useful for standard resource types e.g to configure a inventory of a ConfigMap
	Namespace    string   `json:"namespace,omitempty"`    // If omitted, applies to all namespaces; otherwise, this takes priority to allow namespace specific configurations
	Users        []string `json:"users,omitempty"`        // If omitted applies to all users if set applies to the list of users (based on authentication)
	Filters      []Filter `json:"filters,omitempty"`      // The list of filters to be applied see go/gdch-log-compliance-santitzer
}

// LogFile represents a log file configuration.
type LogFile struct {
	Name string `json:"name,omitempty"` // name. of the entry for easy reference
	// +kubebuilder:validation:Required
	Path string `json:"path"` // path of the file in the file system
}

// Syslog represents a syslog configuration.
type Syslog struct {
	Name string `json:"name,omitempty"` // name. of the entry for easy reference"`
	// +kubebuilder:validation:Required
	AuditLoggingTargetName string `json:"auditLoggingTargetName"` // name of the AuditLoggingTarget routing to Syslog
	// +kubebuilder:validation:Required
	AuditLoggingTargetNamespace string `json:"auditLoggingTargetNamespace"` // namespace of the AuditLoggingTarget
}

type AuditlogInventorySpec struct {
	// +kubebuilder:validation:Required
	OC        string           `json:"oc"`                  // name of the OC that owns this inventory
	ApiServer []ApiServerEntry `json:"apiServer,omitempty"` // list of all audit log entries generated by the API
	LogFiles  []LogFile        `json:"logFiles,omitempty"`  // list of all audit logs files written by the OC
	Syslogs   []Syslog         `json:"syslogs,omitempty"`   // list of audit logs send via syslog by the OC
}

type AuditlogInventoryStatus struct {
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// +genclient
// +kubebuilder:object:root=true
// +kubebuilder:storageversion
// +kubebuilder:subresource:status
// +gdcloud:manifest:relevant=false,oc=log
// Defines the Schema for the AuditlogInventory API.
type AuditlogInventory struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AuditlogInventorySpec   `json:"spec"`
	Status            AuditlogInventoryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:storageversion
// Contains a list of AuditlogInventory.
type AuditlogInventoryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AuditlogInventory `json:"items"`
}

func init() {
	SchemeBuilder.Register(&AuditlogInventory{}, &AuditlogInventoryList{})
}
