filegroup(
    name = "v1alpha1_srcs",
    srcs = [
        "//pkg/apis/public/hsm/v1alpha1:v1alpha1_api_srcs",
    ],
    visibility = [
        # No new dependencies, please use v1.
        "//pkg/apis:__pkg__",
    ],
)

filegroup(
    name = "v1_srcs",
    srcs = [
        "//pkg/apis/public/hsm/v1:v1_api_srcs",
    ],
    visibility = ["//visibility:public"],
)
