// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImportSpec) DeepCopyInto(out *ImportSpec) {
	*out = *in
	in.CommonImportSpec.DeepCopyInto(&out.CommonImportSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImportSpec.
func (in *ImportSpec) DeepCopy() *ImportSpec {
	if in == nil {
		return nil
	}
	out := new(ImportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImportStatus) DeepCopyInto(out *ImportStatus) {
	*out = *in
	in.ImportStatus.DeepCopyInto(&out.ImportStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImportStatus.
func (in *ImportStatus) DeepCopy() *ImportStatus {
	if in == nil {
		return nil
	}
	out := new(ImportStatus)
	in.DeepCopyInto(out)
	return out
}
