// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	marketplacev1 "github.com/googlecloudplatform/google-distributed-cloud-apis/pkg/apis/public/global/marketplace/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogBundle) DeepCopyInto(out *CatalogBundle) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogBundle.
func (in *CatalogBundle) DeepCopy() *CatalogBundle {
	if in == nil {
		return nil
	}
	out := new(CatalogBundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CatalogBundle) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogBundleList) DeepCopyInto(out *CatalogBundleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CatalogBundle, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogBundleList.
func (in *CatalogBundleList) DeepCopy() *CatalogBundleList {
	if in == nil {
		return nil
	}
	out := new(CatalogBundleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CatalogBundleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogBundleSpec) DeepCopyInto(out *CatalogBundleSpec) {
	*out = *in
	in.ServiceCatalog.DeepCopyInto(&out.ServiceCatalog)
	if in.ServiceDescriptions != nil {
		in, out := &in.ServiceDescriptions, &out.ServiceDescriptions
		*out = make([]marketplacev1.ServiceDescriptionReplica, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServiceVersions != nil {
		in, out := &in.ServiceVersions, &out.ServiceVersions
		*out = make([]marketplacev1.ServiceVersionReplica, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogBundleSpec.
func (in *CatalogBundleSpec) DeepCopy() *CatalogBundleSpec {
	if in == nil {
		return nil
	}
	out := new(CatalogBundleSpec)
	in.DeepCopyInto(out)
	return out
}
