// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by bazel. DO NOT EDIT.

package v1alpha1

import (
	"gke-internal.googlesource.com/private-cloud/pkg/apis/common/global/v1alpha1"
)

var _ v1alpha1.MuxReplicaInterface = &FlowTaggerReplica{}

func (r *FlowTaggerReplica) GetSpec() any {
	return v1alpha1.NewTypedFieldAccessor(&r.Spec).GetField()
}

func (r *FlowTaggerReplica) SetSpec(spec any) error {
	return v1alpha1.NewTypedFieldAccessor(&r.Spec).SetField(spec)
}

func (r *FlowTaggerReplica) GetStatus() any {
	return v1alpha1.NewTypedFieldAccessor(&r.Status).GetField()
}

func (r *FlowTaggerReplica) SetStatus(status any) error {
	return v1alpha1.NewTypedFieldAccessor(&r.Status).SetField(status)
}

var _ v1alpha1.MuxStatusInterface = &FlowTaggerStatus{}

func (s *FlowTaggerStatus) GetZones() v1alpha1.ListMap[string, v1alpha1.ZoneStatusInterface] {
	return v1alpha1.NewZoneStatusListAccessor(&s.Zones).GetZones()
}

func (s *FlowTaggerStatus) SetZones(zones v1alpha1.ListMap[string, v1alpha1.ZoneStatusInterface]) error {
	return v1alpha1.NewZoneStatusListAccessor(&s.Zones).SetZones(zones)
}

var _ v1alpha1.ZoneStatusInterface = &FlowTaggerZoneStatus{}

func (s *FlowTaggerZoneStatus) GetReplicaStatus() any {
	return v1alpha1.NewTypedFieldAccessor(&s.ReplicaStatus).GetField()
}

func (s *FlowTaggerZoneStatus) SetReplicaStatus(replicaStatus any) error {
	return v1alpha1.NewTypedFieldAccessor(&s.ReplicaStatus).SetField(replicaStatus)
}

var _ v1alpha1.MuxResourceInterface = &FlowTagger{}

func (r *FlowTagger) GetSpec() any {
	return v1alpha1.NewTypedFieldAccessor(&r.Spec).GetField()
}

func (r *FlowTagger) SetSpec(spec any) error {
	return v1alpha1.NewTypedFieldAccessor(&r.Spec).SetField(spec)
}

func (r *FlowTagger) GetStatus() v1alpha1.MuxStatusInterface {
	return v1alpha1.NewMuxStatusAccessor(&r.Status).GetStatus()
}

func (r *FlowTagger) SetStatus(status v1alpha1.MuxStatusInterface) error {
	return v1alpha1.NewMuxStatusAccessor(&r.Status).SetStatus(status)
}
