// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowTagger) DeepCopyInto(out *FlowTagger) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowTagger.
func (in *FlowTagger) DeepCopy() *FlowTagger {
	if in == nil {
		return nil
	}
	out := new(FlowTagger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FlowTagger) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowTaggerEntity) DeepCopyInto(out *FlowTaggerEntity) {
	*out = *in
	if in.ResourceInfo != nil {
		in, out := &in.ResourceInfo, &out.ResourceInfo
		*out = new(ResourceInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowTaggerEntity.
func (in *FlowTaggerEntity) DeepCopy() *FlowTaggerEntity {
	if in == nil {
		return nil
	}
	out := new(FlowTaggerEntity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowTaggerList) DeepCopyInto(out *FlowTaggerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FlowTagger, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowTaggerList.
func (in *FlowTaggerList) DeepCopy() *FlowTaggerList {
	if in == nil {
		return nil
	}
	out := new(FlowTaggerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FlowTaggerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowTaggerReplica) DeepCopyInto(out *FlowTaggerReplica) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowTaggerReplica.
func (in *FlowTaggerReplica) DeepCopy() *FlowTaggerReplica {
	if in == nil {
		return nil
	}
	out := new(FlowTaggerReplica)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FlowTaggerReplica) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowTaggerReplicaList) DeepCopyInto(out *FlowTaggerReplicaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FlowTaggerReplica, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowTaggerReplicaList.
func (in *FlowTaggerReplicaList) DeepCopy() *FlowTaggerReplicaList {
	if in == nil {
		return nil
	}
	out := new(FlowTaggerReplicaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FlowTaggerReplicaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowTaggerSpec) DeepCopyInto(out *FlowTaggerSpec) {
	*out = *in
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(FlowTaggerEntity)
		(*in).DeepCopyInto(*out)
	}
	if in.Destination != nil {
		in, out := &in.Destination, &out.Destination
		*out = new(FlowTaggerEntity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowTaggerSpec.
func (in *FlowTaggerSpec) DeepCopy() *FlowTaggerSpec {
	if in == nil {
		return nil
	}
	out := new(FlowTaggerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowTaggerStatus) DeepCopyInto(out *FlowTaggerStatus) {
	*out = *in
	in.MuxStatus.DeepCopyInto(&out.MuxStatus)
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]FlowTaggerZoneStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowTaggerStatus.
func (in *FlowTaggerStatus) DeepCopy() *FlowTaggerStatus {
	if in == nil {
		return nil
	}
	out := new(FlowTaggerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowTaggerZoneStatus) DeepCopyInto(out *FlowTaggerZoneStatus) {
	*out = *in
	in.ZoneStatus.DeepCopyInto(&out.ZoneStatus)
	in.ReplicaStatus.DeepCopyInto(&out.ReplicaStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowTaggerZoneStatus.
func (in *FlowTaggerZoneStatus) DeepCopy() *FlowTaggerZoneStatus {
	if in == nil {
		return nil
	}
	out := new(FlowTaggerZoneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceInfo) DeepCopyInto(out *ResourceInfo) {
	*out = *in
	in.TypedObjectReference.DeepCopyInto(&out.TypedObjectReference)
	in.ClusterRef.DeepCopyInto(&out.ClusterRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceInfo.
func (in *ResourceInfo) DeepCopy() *ResourceInfo {
	if in == nil {
		return nil
	}
	out := new(ResourceInfo)
	in.DeepCopyInto(out)
	return out
}
