// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveredVM) DeepCopyInto(out *DiscoveredVM) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveredVM.
func (in *DiscoveredVM) DeepCopy() *DiscoveredVM {
	if in == nil {
		return nil
	}
	out := new(DiscoveredVM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiscoveredVM) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveredVMDetails) DeepCopyInto(out *DiscoveredVMDetails) {
	*out = *in
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveredVMDetails.
func (in *DiscoveredVMDetails) DeepCopy() *DiscoveredVMDetails {
	if in == nil {
		return nil
	}
	out := new(DiscoveredVMDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveredVMList) DeepCopyInto(out *DiscoveredVMList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DiscoveredVM, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveredVMList.
func (in *DiscoveredVMList) DeepCopy() *DiscoveredVMList {
	if in == nil {
		return nil
	}
	out := new(DiscoveredVMList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiscoveredVMList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveredVMSpec) DeepCopyInto(out *DiscoveredVMSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveredVMSpec.
func (in *DiscoveredVMSpec) DeepCopy() *DiscoveredVMSpec {
	if in == nil {
		return nil
	}
	out := new(DiscoveredVMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveredVMStatus) DeepCopyInto(out *DiscoveredVMStatus) {
	*out = *in
	in.VMDetails.DeepCopyInto(&out.VMDetails)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveredVMStatus.
func (in *DiscoveredVMStatus) DeepCopy() *DiscoveredVMStatus {
	if in == nil {
		return nil
	}
	out := new(DiscoveredVMStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationSource) DeepCopyInto(out *MigrationSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationSource.
func (in *MigrationSource) DeepCopy() *MigrationSource {
	if in == nil {
		return nil
	}
	out := new(MigrationSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MigrationSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationSourceList) DeepCopyInto(out *MigrationSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MigrationSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationSourceList.
func (in *MigrationSourceList) DeepCopy() *MigrationSourceList {
	if in == nil {
		return nil
	}
	out := new(MigrationSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MigrationSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationSourceSpec) DeepCopyInto(out *MigrationSourceSpec) {
	*out = *in
	in.LastRequestedDiscovery.DeepCopyInto(&out.LastRequestedDiscovery)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationSourceSpec.
func (in *MigrationSourceSpec) DeepCopy() *MigrationSourceSpec {
	if in == nil {
		return nil
	}
	out := new(MigrationSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationSourceStatus) DeepCopyInto(out *MigrationSourceStatus) {
	*out = *in
	if in.DiscoveryStatus != nil {
		in, out := &in.DiscoveryStatus, &out.DiscoveryStatus
		*out = new(DiscoveryStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationSourceStatus.
func (in *MigrationSourceStatus) DeepCopy() *MigrationSourceStatus {
	if in == nil {
		return nil
	}
	out := new(MigrationSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMMigration) DeepCopyInto(out *VMMigration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMMigration.
func (in *VMMigration) DeepCopy() *VMMigration {
	if in == nil {
		return nil
	}
	out := new(VMMigration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VMMigration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMMigrationList) DeepCopyInto(out *VMMigrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VMMigration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMMigrationList.
func (in *VMMigrationList) DeepCopy() *VMMigrationList {
	if in == nil {
		return nil
	}
	out := new(VMMigrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VMMigrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMMigrationSpec) DeepCopyInto(out *VMMigrationSpec) {
	*out = *in
	out.DiscoveredVMRef = in.DiscoveredVMRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMMigrationSpec.
func (in *VMMigrationSpec) DeepCopy() *VMMigrationSpec {
	if in == nil {
		return nil
	}
	out := new(VMMigrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMMigrationStatus) DeepCopyInto(out *VMMigrationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMMigrationStatus.
func (in *VMMigrationStatus) DeepCopy() *VMMigrationStatus {
	if in == nil {
		return nil
	}
	out := new(VMMigrationStatus)
	in.DeepCopyInto(out)
	return out
}
