load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("//build/rules/controller_gen:aspect.bzl", "kubebuilder_analyze")
load("//build/rules/controller_gen:kubebuilder.bzl", "api_package")

# gazelle:exclude zz_generated.*.go

kubebuilder_analyze(
    name = "easysaas_typedata",
    srcs = [
        "errors.go",
        "groupversion_info.go",
        "localrollout.go",
        "moduleinstance.go",
        "saasinstance.go",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//vendor/k8s.io/apimachinery/pkg/api/meta",
        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
        "//vendor/k8s.io/apimachinery/pkg/runtime",
        "//vendor/k8s.io/apimachinery/pkg/runtime/schema",
        "//vendor/sigs.k8s.io/controller-runtime/pkg/scheme",
    ],
)

api_package(
    name = "easysaas_api",
    targets = [":easysaas_typedata"],
    visibility = ["//visibility:public"],
)

go_library(
    name = "easysaas",
    srcs = [
        "errors.go",
        "groupversion_info.go",
        "localrollout.go",
        "moduleinstance.go",
        "saasinstance.go",
        "zz_generated.deepcopy.go",  # keep
    ],
    importpath = "github.com/googlecloudplatform/google-distributed-cloud-apis/pkg/apis/public/dbs/fleet/easysaas/v1",
    visibility = ["//visibility:public"],
    deps = [
        "//vendor/k8s.io/apimachinery/pkg/api/meta",
        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
        "//vendor/k8s.io/apimachinery/pkg/runtime",  # keep
        "//vendor/k8s.io/apimachinery/pkg/runtime/schema",
        "//vendor/sigs.k8s.io/controller-runtime/pkg/scheme",
    ],
)
