load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")
load("//build/rules/controller_gen:aspect.bzl", "kubebuilder_analyze")
load("//build/rules/controller_gen:kubebuilder.bzl", "api_package")

# gazelle:exclude zz_generated.*.go

kubebuilder_analyze(
    name = "v1alpha1_typedata",
    srcs = [
        "groupversion_info.go",
        "loggingrule_types.go",
        "loggingtarget_types.go",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/apis/public",
        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
        "//vendor/k8s.io/apimachinery/pkg/runtime/schema",
        "//vendor/sigs.k8s.io/cluster-operators/logmon-operator/api/v1alpha1",
        "//vendor/sigs.k8s.io/controller-runtime/pkg/scheme",
    ],
)

kubebuilder_analyze(
    name = "mgmt_v1alpha1_typedata",
    srcs = [
        "groupversion_info.go",
        "loggingrule_types.go",
        "loggingtarget_types.go",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/apis/public",
        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
        "//vendor/k8s.io/apimachinery/pkg/runtime/schema",
        "//vendor/sigs.k8s.io/cluster-operators/logmon-operator/api/v1alpha1",
        "//vendor/sigs.k8s.io/controller-runtime/pkg/scheme",
    ],
)

api_package(
    name = "v1alpha1_api",
    targets = [":mgmt_v1alpha1_typedata"],
)

go_library(
    name = "v1alpha1",
    srcs = [
        "generated.deepcopy.go",  # keep
        "groupversion_info.go",
        "loggingrule_conversion.go",
        "loggingrule_types.go",
        "loggingtarget_conversion.go",
        "loggingtarget_types.go",
    ],
    importpath = "gke-internal.googlesource.com/private-cloud/pkg/apis/public/logging/v1alpha1",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/apis/public",
        "//pkg/apis/public/logging/v1",
        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
        "//vendor/k8s.io/apimachinery/pkg/runtime",  # keep
        "//vendor/k8s.io/apimachinery/pkg/runtime/schema",
        "//vendor/sigs.k8s.io/cluster-operators/logmon-operator/api/v1alpha1",
        "//vendor/sigs.k8s.io/controller-runtime/pkg/conversion",
        "//vendor/sigs.k8s.io/controller-runtime/pkg/scheme",
    ],
)

go_test(
    name = "v1alpha1_test",
    srcs = [
        "loggingrule_conversions_test.go",
        "loggingtarget_conversions_test.go",
    ],
    embed = [":v1alpha1"],
    deps = [
        "//pkg/apis/public/logging/v1",
        "//vendor/github.com/google/go-cmp/cmp",
        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
        "//vendor/sigs.k8s.io/cluster-operators/logmon-operator/api/v1alpha1",
    ],
)
