// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	corev1alpha1 "github.com/googlecloudplatform/google-distributed-cloud-apis/pkg/apis/core/v1alpha1"
)

// TODO(b/200285234): This file is heavily patterned off of:
//   cs//depot/google3/blaze-out/genfiles/google/cloud/gkebackup/v1alpha1/backup.pb.go
// Going forward, we should come up with a good process to keep these
// relatively in sync.

// Defines the desired state of the backup.
type BackupSpec struct {
	// The name of the cluster that is backed up.
	// By default, it is the cluster in which this backup is created.
	// +optional
	ClusterName string `json:"clusterName,omitempty" reflect:"unexport"`

	// The name of the backup plan from which this backup was created.
	// +kubebuilder:validation:Required
	BackupPlanName string `json:"backupPlanName,omitempty" reflect:"unexport"`
	// A configuration that is used when this backup is generated from the
	// given backup plan. This must be copied from the backup plan that this backup
	// was generated by, rather than a reference.
	// This field must not be set by the user, and must only be set by the
	// backup plan scheduler and the `ManualBackupRequest` resource.
	// +kubebuilder:validation:Required
	BackupConfig BackupConfig `json:"backupConfig,omitempty" reflect:"unexport"`

	// An optional string description of the Backup. This field has no impact on functionality.
	Description string `json:"description,omitempty" reflect:"unexport"`

	// Specifies whether the backup resource was
	// created manually. If `True`, this backup has been created manually,
	// If `False`, this Backup has been created automatically from the
	// backup plan schedule.
	// +optional
	// +kubebuilder:default:=false
	Manual bool `json:"manual,omitempty" reflect:"unexport"`
	// The number of days from the `create_time` of this
	// backup for which deletion is blocked.
	// For backups created automatically from a backup schedule, this field is set to
	// the value of `BackupPlan.RetentionPolicy.backup_delete_block_days`.
	// For backups created manually that leave this field unspecified, the service
	// assigns the value of `BackupPlan.RetentionPolicy.backup_delete_block_days`.
	// If a backup is created where the value of this field is less than the value of
	// `BackupPlan.RetentionPolicy.backup_delete_block_days`, an invalid
	// response is returned from the service.
	// This field must be an integer value between `0-90`.
	// This field must only be increased by an update request, or an invalid
	// response is returned by the service.
	// Note, this field only applies to backups with a `Succeeded` state.
	// Default to `0`.
	// +optional
	// +kubebuilder:default:=0
	DeleteLockDays uint `json:"deleteLockDays,omitempty" reflect:"unexport"`
	// The number of days to keep
	// this backup for, after which it is automatically deleted.
	// This is calculated from the `create_time` of the backup.
	// If this field is not specified or set to `0`, it means the backup is not automatically
	// deleted.
	// For backups automatically created from a a backup schedule, this field is assigned
	// the value of `BackupPlan.RetentionPolicy.backup_retain_days`.
	// For backups created manually that leave this field unspecified, the service
	// assigns the value of `BackupPlan.RetentionPolicy.backup_retain_days`.
	// If a backup is created where the value of this field is less than
	// the value of `delete_lock_days`, an invalid response is returned by the service.
	// This field must only be increased by an update request, or an invalid
	// response is returned by the service.
	// Default to `0`.
	// +optional
	// +kubebuilder:default:=0
	RetainDays uint `json:"retainDays,omitempty" reflect:"unexport"`
}

// Represents the metadata of the cluster.
type ClusterMetadata struct {
	// The name of the source cluster from where the backup has been created from.
	// +kubebuilder:validation:Optional
	ClusterName string `json:"clusterName,omitempty" reflect:"unexport"`

	// The Kubernetes server version.
	// +kubebuilder:validation:Optional
	K8SVersion string `json:"k8sVersion,omitempty" reflect:"unexport"`

	///// P2 Fields, Do Not Need To Be Implemented for V0 /////

	// The platform version types that can be assigned to PlatformVersion.
	// For example, `GpcVersion`.
	// +optional
	PlatformVersion *PlatformVersion `json:"platformVersion" reflect:"unexport"`
}

// The various states a backup can be in.
// +kubebuilder:validation:Enum=Unspecified;Creating;InProgress;Succeeded;Failed;Deleting;DeleteFailed;PartiallySucceeded
type BackupState string

// TODO(b/200285235): Should this be merged with BackupJob Phase?
const (
	BackupStateUnspecified        BackupState = "Unspecified"
	BackupStateCreating           BackupState = "Creating"
	BackupStateInProgress         BackupState = "InProgress"
	BackupStateSucceeded          BackupState = "Succeeded"
	BackupStateFailed             BackupState = "Failed"
	BackupStateDeleting           BackupState = "Deleting"
	BackupStateDeletedFailed      BackupState = "DeleteFailed"
	BackupStatePartiallySucceeded BackupState = "PartiallySucceeded"
)

// Defines the version of the platform.
type PlatformVersion struct {
	// The Google Private Cloud version.
	// +optional
	GpcVersion string `json:"gpcVersion,omitempty" reflect:"unexport"`
}

const (
	BackupConditionSucceeded = "Succeeded"
)

// The various phases a backup execution can go through.
// +kubebuilder:validation:Enum=Pending;Scheduled;Initializing;ConfigBackup;PreHook;Snapshot;PostHook;Uploading;Finalizing
type BackupPhase string

const (
	BackupPhasePending      BackupPhase = "Pending"
	BackupPhaseScheduled    BackupPhase = "Scheduled"
	BackupPhaseInitializing BackupPhase = "Initializing"
	BackupPhaseConfigBackup BackupPhase = "ConfigBackup"
	BackupPhasePreHook      BackupPhase = "PreHook"
	BackupPhaseSnapshot     BackupPhase = "Snapshot"
	BackupPhasePostHook     BackupPhase = "PostHook"
	BackupPhaseUploading    BackupPhase = "Uploading"
	BackupPhaseFinalizing   BackupPhase = "Finalizing"
)

// BackupConditionReason defines the set of allowable reason strings for Backup conditions.
type BackupConditionReason string

const (
	// ReasonCompleted indicates a phase has successfully finished.
	ReasonCompleted BackupConditionReason = "Completed"

	// ReasonStarted indicates a phase has started but not finished.
	ReasonStarted BackupConditionReason = "Started"

	// ReasonInitialized indicates the backup has been successfully initialized.
	ReasonInitialized BackupConditionReason = "Initialized"

	// ReasonFailed is used when a condition fails.
	ReasonFailed BackupConditionReason = "Failed"
)

// Defines the observed state of a backup.
type BackupStatus struct {
	// The metadata of the cluster.
	// +optional
	ClusterMetadata *ClusterMetadata `json:"clusterMetadata,omitempty" reflect:"unexport"`
	// Specifies whether a backup job has been created for this backup.
	JobCreated bool `json:"jobCreated,omitempty" reflect:"unexport"`
	// The current state of the backup.
	// +optional
	State BackupState `json:"state,omitempty" reflect:"unexport"`
	// A human-readable description of why the backup is in the current state.
	// +optional
	StateReason string `json:"reason,omitempty"`
	// The most recent errors with the observed times included.
	// +optional
	ErrorStatus *corev1alpha1.ErrorStatus `json:"errorStatus,omitempty"`
	// Conditions represents the observations of this backup's current state.
	// Known condition types: Succeeded
	Conditions []metav1.Condition `json:"conditions,omitempty" patchStrategy:"merge" patchMergeKey:"type" reflect:"unexport"`
	// The timestamp of when this backup resource was created. This can
	// be converted to and from [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt).
	// +optional
	CreateTime *metav1.Time `json:"createTime,omitempty" reflect:"unexport"`
	// The timestamp of when this backup plan was last updated.
	// This can be converted to and from
	// [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt).
	// +optional
	UpdateTime *metav1.Time `json:"updateTime,omitempty" reflect:"unexport"`
	// The total number of resources backed up.
	// +optional
	ResourceCount int64 `json:"resourceCount,omitempty" reflect:"unexport"`
	// The total number of volumes backed up.
	// +optional
	VolumeCount int64 `json:"volumeCount,omitempty" reflect:"unexport"`
	// The total size, measured in bytes.
	// +optional
	SizeBytes int64 `json:"sizeBytes,omitempty" reflect:"unexport"`
	// The total number of workload pods backed up.
	// +optional
	PodCount int64 `json:"podCount,omitempty" reflect:"unexport"`
	// The total number of system pods backed up. These pods are excluded from billing.
	// +optional
	SystemPodCount int64 `json:"systemPodCount,omitempty" reflect:"unexport"`
	// The total number of virtual machines backed up.
	// +optional
	VmCount int64 `json:"vmCount,omitempty" reflect:"unexport"`
	// PodCountPerNamespace maps namespace to the number of workload pods backed up in that namespace.
	// +optional
	PodCountPerNamespace map[string]int64 `json:"podCountPerNamespace,omitempty" reflect:"unexport"`
	// VmCountPerNamespace maps namespace to the number of virtual machines backed up in that namespace.
	// +optional
	VmCountPerNamespace map[string]int64 `json:"vmCountPerNamespace,omitempty" reflect:"unexport"`

	///// P2 Fields, Do Not Need To Be Implemented for V0 /////

	// The time when the deletion lock
	// will expire. This is an output only field calculated from the combined value of `create_time` and
	// `delete_lock_days`, and is updated accordingly when the
	// `delete_lock_days` field of a backup is updated.
	// Note, this field only applies to backups with a `Succeeded` state.
	// +optional
	DeleteLockExpireTime *metav1.Time `json:"deleteLockExpireTime,omitempty" reflect:"unexport"`
	// The time when the backup is
	// automatically deleted. It's an output only field calculated from the combined value
	// of `create_time` and `retain_days`, and is updated accordingly when the
	// `retain_days` field of a backup has been updated.
	// +optional
	RetainExpireTime *metav1.Time `json:"retainExpireTime,omitempty" reflect:"unexport"`
	// The completion time of the backup.
	// +optional
	CompleteTime *metav1.Time `json:"completeTime,omitempty" reflect:"unexport"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion
// +kubebuilder:printcolumn:name="State",type="string",JSONPath=".status.state"
// +kubebuilder:printcolumn:name="CreateTime",type="string",JSONPath=".status.createTime"

// +genclient
// +gdcloud:manifest:relevant=false,oc=back
// Defines the schema for the `Backup` API.
type Backup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   BackupSpec   `json:"spec,omitempty"`
	Status BackupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// Contains a list of backups.
type BackupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Backup `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Backup{}, &BackupList{})
}
