// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	corev1alpha1 "github.com/googlecloudplatform/google-distributed-cloud-apis/pkg/apis/core/v1alpha1"
)

// Represents the retention policy for a Backup
type BackupRetentionPolicy struct {
	// The number of days from the creation of this backup
	// backup for which deletion is blocked.
	// For backups created automatically from a backup schedule, this field is set to
	// the value of `ClusterBackupPlan.RetentionPolicy.backup_delete_block_days`.
	// For backups created manually that leave this field unspecified, the service
	// assigns the value of `ClusterBackupPlan.RetentionPolicy.backup_delete_block_days`.
	// If a backup is created where the value of this field is less than the value of
	// `ClusterBackupPlan.RetentionPolicy.backup_delete_block_days`, an invalid
	// response is returned from the service.
	// This field must be an integer value between `0-90`.
	// This field must only be increased by an update request, or an invalid
	// response is returned by the service.
	// Note, this field only applies to backups with a `Succeeded` state.
	// +optional
	DeleteLockDays *uint `json:"deleteLockDays,omitempty"`

	// The number of days to keep
	// this cluster backup for, after which it is automatically deleted.
	// This is calculated from the `create_time` of the cluster backup.
	// If this field is not specified or set to `0`, it means the backup is not automatically
	// deleted.
	// For cluster backups automatically created from a schedule, this field is assigned
	// the value of `ClusterBackupPlan.RetentionPolicy.backup_retain_days`.
	// For backups created manually that leave this field unspecified, the service
	// assigns the value of `ClusterBackupPlan.RetentionPolicy.backup_retain_days`.
	// If a backup is created where the value of this field is less than
	// the value of `delete_lock_days`, an invalid response is returned by the service.
	// This field must only be increased by an update request, or an invalid
	// response is returned by the service.
	// +optional
	RetainDays *uint `json:"retainDays,omitempty"`
}

// Represents an API that wraps around the Backup custom resource.
// They are mostly identical, but there are some fields that are selectively omitted.
type ClusterBackupSpec struct {
	// The name of the cluster that will backed up.
	// +kubebuilder:validation:XValidation:rule=(self == oldSelf)
	// +kubebuilder:validation:Required
	TargetCluster TargetCluster `json:"targetCluster"`

	// The name of the cluster backup plan from which this backup was created.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule=(self == oldSelf)
	ClusterBackupPlanName string `json:"clusterBackupPlanName,omitempty"`

	// A configuration that is used when this backup is generated from the
	// given backup plan. This must be copied from the cluster backup plan that this
	// cluster backup was generated by, rather than a reference.
	// This field must not be set by the user, and must only be set by the
	// backup plan scheduler and the `ManualBackupRequest` resource.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule=(self == oldSelf)
	ClusterBackupConfig ClusterBackupConfig `json:"backupConfig,omitempty"`

	// An optional string description of the backup. This field has no impact on functionality.
	Description string `json:"description,omitempty"`

	// Specifies whether the cluster backup resource was
	// created manually. If `True`, this backup has been created manually,
	// If `False`, this cluster backup has been created automatically from the
	// backup plan schedule.
	// +optional
	// +kubebuilder:default:=false
	Manual bool `json:"manual,omitempty"`

	// Retention policy for the Backup.
	// +optional
	RetentionPolicy *BackupRetentionPolicy `json:"retentionPolicy,omitempty"`
}

// Defines the observed state of a cluster backup.
type ClusterBackupStatus struct {
	// The metadata of the cluster.
	// +optional
	ClusterMetadata *ClusterMetadata `json:"clusterMetadata,omitempty"`

	// Specifies the status of the cluster backup. Supported conditions include `JobCreated`, `Succeeded`.
	Conditions []metav1.Condition `json:"conditions,omitempty"`

	// Specifies whether a backup job has been created for this cluster backup.
	JobCreated bool `json:"jobCreated,omitempty" `

	// The current state of the cluster backup.
	// +optional
	State BackupState `json:"state,omitempty"`

	// A human-readable description of why the backup is in the current state.
	// +optional
	StateReason string `json:"stateReason,omitempty"`

	// The most recent errors with the observed times included.
	// +optional
	ErrorStatus *corev1alpha1.ErrorStatus `json:"errorStatus,omitempty"`

	// The timestamp of when this backup resource was created. This can
	// be converted to and from [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt).
	// +optional
	CreateTime *metav1.Time `json:"createTime,omitempty" reflect:"unexport"`

	// The timestamp of when this cluster backup was last updated.
	// This can be converted to and from
	// [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt).
	// +optional
	UpdateTime *metav1.Time `json:"updateTime,omitempty"`

	// The total number of resources backed up.
	// +optional
	ResourceCount int64 `json:"resourceCount,omitempty"`

	// The total number of volumes backed up.
	// +optional
	VolumeCount int64 `json:"volumeCount,omitempty"`

	// The total size, measured in bytes.
	// +optional
	SizeBytes int64 `json:"sizeBytes,omitempty"`

	// The total number of workload pods backed up.
	// +optional
	PodCount int64 `json:"podCount,omitempty"`

	// PodCountPerNamespace maps namespace to the number of workload pods backed up in that namespace.
	// +optional
	PodCountPerNamespace map[string]int64 `json:"podCountPerNamespace,omitempty"`

	// VmCountPerNamespace maps namespace to the number of virtual machines backed up in that namespace.
	// +optional
	VmCountPerNamespace map[string]int64 `json:"vmCountPerNamespace,omitempty"`

	// The time when the deletion lock
	// will expire. This is an output only field calculated from the combined value of `create_time` and
	// `delete_lock_days`, and is updated accordingly when the
	// `delete_lock_days` field of a cluster backup is updated.
	// Note, this field only applies to cluster backups with a `Succeeded` state.
	// +optional
	DeleteLockExpireTime *metav1.Time `json:"deleteLockExpireTime,omitempty"`

	// The time when the cluster backup is
	// automatically deleted. It's an output only field calculated from the combined value
	// of `create_time` and `retain_days`, and is updated accordingly when the
	// `retain_days` field of a cluster backup has been updated.
	// +optional
	RetainExpireTime *metav1.Time `json:"retainExpireTime,omitempty"`

	// The completion time of the cluster backup.
	// +optional
	CompleteTime *metav1.Time `json:"completeTime,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion
// +kubebuilder:printcolumn:name="State",type="string",JSONPath=".status.state"
// +kubebuilder:printcolumn:name="CreateTime",type="string",JSONPath=".status.createTime"
// +genclient
// +gdcloud:manifest:relevant=true,oc=back,component=backup,entities="cluster-backups"
// +gdcloud:manifest:verbs=describe;list
// +gdcloud:manifest:rbac="describe,list:organization-cluster-backup-admin"
type ClusterBackup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ClusterBackupSpec   `json:"spec,omitempty"`
	Status            ClusterBackupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// Represents a list of cluster backups.
type ClusterBackupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ClusterBackup `json:"items"`
}

func init() {
	SchemeBuilder.Register(
		&ClusterBackup{},
		&ClusterBackupList{},
	)
}
