// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AEADKey) DeepCopyInto(out *AEADKey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AEADKey.
func (in *AEADKey) DeepCopy() *AEADKey {
	if in == nil {
		return nil
	}
	out := new(AEADKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AEADKey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AEADKeyList) DeepCopyInto(out *AEADKeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AEADKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AEADKeyList.
func (in *AEADKeyList) DeepCopy() *AEADKeyList {
	if in == nil {
		return nil
	}
	out := new(AEADKeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AEADKeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AEADKeySpec) DeepCopyInto(out *AEADKeySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AEADKeySpec.
func (in *AEADKeySpec) DeepCopy() *AEADKeySpec {
	if in == nil {
		return nil
	}
	out := new(AEADKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AEADKeyStatus) DeepCopyInto(out *AEADKeyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EncryptedKeyMaterial != nil {
		in, out := &in.EncryptedKeyMaterial, &out.EncryptedKeyMaterial
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AEADKeyStatus.
func (in *AEADKeyStatus) DeepCopy() *AEADKeyStatus {
	if in == nil {
		return nil
	}
	out := new(AEADKeyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CryptoBackend) DeepCopyInto(out *CryptoBackend) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CryptoBackend.
func (in *CryptoBackend) DeepCopy() *CryptoBackend {
	if in == nil {
		return nil
	}
	out := new(CryptoBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CryptoBackend) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CryptoBackendList) DeepCopyInto(out *CryptoBackendList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CryptoBackend, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CryptoBackendList.
func (in *CryptoBackendList) DeepCopy() *CryptoBackendList {
	if in == nil {
		return nil
	}
	out := new(CryptoBackendList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CryptoBackendList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CryptoBackendSpec) DeepCopyInto(out *CryptoBackendSpec) {
	*out = *in
	if in.ThalesLunaHSM != nil {
		in, out := &in.ThalesLunaHSM, &out.ThalesLunaHSM
		*out = new(ThalesLunaHSMConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CryptoBackendSpec.
func (in *CryptoBackendSpec) DeepCopy() *CryptoBackendSpec {
	if in == nil {
		return nil
	}
	out := new(CryptoBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CryptoBackendStatus) DeepCopyInto(out *CryptoBackendStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ThalesLunaHSM != nil {
		in, out := &in.ThalesLunaHSM, &out.ThalesLunaHSM
		*out = new(ThalesLunaHSMStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CryptoBackendStatus.
func (in *CryptoBackendStatus) DeepCopy() *CryptoBackendStatus {
	if in == nil {
		return nil
	}
	out := new(CryptoBackendStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyExport) DeepCopyInto(out *KeyExport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyExport.
func (in *KeyExport) DeepCopy() *KeyExport {
	if in == nil {
		return nil
	}
	out := new(KeyExport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeyExport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyExportList) DeepCopyInto(out *KeyExportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeyExport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyExportList.
func (in *KeyExportList) DeepCopy() *KeyExportList {
	if in == nil {
		return nil
	}
	out := new(KeyExportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeyExportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyExportSpec) DeepCopyInto(out *KeyExportSpec) {
	*out = *in
	in.Context.DeepCopyInto(&out.Context)
	in.KeyToExport.DeepCopyInto(&out.KeyToExport)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyExportSpec.
func (in *KeyExportSpec) DeepCopy() *KeyExportSpec {
	if in == nil {
		return nil
	}
	out := new(KeyExportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyExportStatus) DeepCopyInto(out *KeyExportStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExportedKey != nil {
		in, out := &in.ExportedKey, &out.ExportedKey
		*out = new(WrappedKey)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyExportStatus.
func (in *KeyExportStatus) DeepCopy() *KeyExportStatus {
	if in == nil {
		return nil
	}
	out := new(KeyExportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyImport) DeepCopyInto(out *KeyImport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyImport.
func (in *KeyImport) DeepCopy() *KeyImport {
	if in == nil {
		return nil
	}
	out := new(KeyImport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeyImport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyImportList) DeepCopyInto(out *KeyImportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeyImport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyImportList.
func (in *KeyImportList) DeepCopy() *KeyImportList {
	if in == nil {
		return nil
	}
	out := new(KeyImportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeyImportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyImportSpec) DeepCopyInto(out *KeyImportSpec) {
	*out = *in
	in.Context.DeepCopyInto(&out.Context)
	if in.KeyToImport != nil {
		in, out := &in.KeyToImport, &out.KeyToImport
		*out = new(WrappedKey)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyImportSpec.
func (in *KeyImportSpec) DeepCopy() *KeyImportSpec {
	if in == nil {
		return nil
	}
	out := new(KeyImportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyImportStatus) DeepCopyInto(out *KeyImportStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.PeerContext.DeepCopyInto(&out.PeerContext)
	in.ImportedKeyRef.DeepCopyInto(&out.ImportedKeyRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyImportStatus.
func (in *KeyImportStatus) DeepCopy() *KeyImportStatus {
	if in == nil {
		return nil
	}
	out := new(KeyImportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyMetadata) DeepCopyInto(out *KeyMetadata) {
	*out = *in
	out.KeyTypeMeta = in.KeyTypeMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyMetadata.
func (in *KeyMetadata) DeepCopy() *KeyMetadata {
	if in == nil {
		return nil
	}
	out := new(KeyMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeySharingContext) DeepCopyInto(out *KeySharingContext) {
	*out = *in
	if in.PublicKey != nil {
		in, out := &in.PublicKey, &out.PublicKey
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeySharingContext.
func (in *KeySharingContext) DeepCopy() *KeySharingContext {
	if in == nil {
		return nil
	}
	out := new(KeySharingContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LunaCredentials) DeepCopyInto(out *LunaCredentials) {
	*out = *in
	out.PSOPasswordRef = in.PSOPasswordRef
	out.COPasswordRef = in.COPasswordRef
	out.CloningDomainRef = in.CloningDomainRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LunaCredentials.
func (in *LunaCredentials) DeepCopy() *LunaCredentials {
	if in == nil {
		return nil
	}
	out := new(LunaCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LunaHAGroupMember) DeepCopyInto(out *LunaHAGroupMember) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LunaHAGroupMember.
func (in *LunaHAGroupMember) DeepCopy() *LunaHAGroupMember {
	if in == nil {
		return nil
	}
	out := new(LunaHAGroupMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedReference) DeepCopyInto(out *NamespacedReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedReference.
func (in *NamespacedReference) DeepCopy() *NamespacedReference {
	if in == nil {
		return nil
	}
	out := new(NamespacedReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerSharingContext) DeepCopyInto(out *PeerSharingContext) {
	*out = *in
	if in.PublicKey != nil {
		in, out := &in.PublicKey, &out.PublicKey
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.PrivateKey != nil {
		in, out := &in.PrivateKey, &out.PrivateKey
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerSharingContext.
func (in *PeerSharingContext) DeepCopy() *PeerSharingContext {
	if in == nil {
		return nil
	}
	out := new(PeerSharingContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectionLevel) DeepCopyInto(out *ProtectionLevel) {
	*out = *in
	if in.CryptoBackendRef != nil {
		in, out := &in.CryptoBackendRef, &out.CryptoBackendRef
		*out = new(NamespacedReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectionLevel.
func (in *ProtectionLevel) DeepCopy() *ProtectionLevel {
	if in == nil {
		return nil
	}
	out := new(ProtectionLevel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotationJob) DeepCopyInto(out *RotationJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotationJob.
func (in *RotationJob) DeepCopy() *RotationJob {
	if in == nil {
		return nil
	}
	out := new(RotationJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RotationJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotationJobList) DeepCopyInto(out *RotationJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RotationJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotationJobList.
func (in *RotationJobList) DeepCopy() *RotationJobList {
	if in == nil {
		return nil
	}
	out := new(RotationJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RotationJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotationJobSpec) DeepCopyInto(out *RotationJobSpec) {
	*out = *in
	if in.TTLSecondsAfterCompletion != nil {
		in, out := &in.TTLSecondsAfterCompletion, &out.TTLSecondsAfterCompletion
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotationJobSpec.
func (in *RotationJobSpec) DeepCopy() *RotationJobSpec {
	if in == nil {
		return nil
	}
	out := new(RotationJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotationJobStatus) DeepCopyInto(out *RotationJobStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotationJobStatus.
func (in *RotationJobStatus) DeepCopy() *RotationJobStatus {
	if in == nil {
		return nil
	}
	out := new(RotationJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SigningKey) DeepCopyInto(out *SigningKey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SigningKey.
func (in *SigningKey) DeepCopy() *SigningKey {
	if in == nil {
		return nil
	}
	out := new(SigningKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SigningKey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SigningKeyList) DeepCopyInto(out *SigningKeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SigningKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SigningKeyList.
func (in *SigningKeyList) DeepCopy() *SigningKeyList {
	if in == nil {
		return nil
	}
	out := new(SigningKeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SigningKeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SigningKeySpec) DeepCopyInto(out *SigningKeySpec) {
	*out = *in
	if in.ProtectionLevel != nil {
		in, out := &in.ProtectionLevel, &out.ProtectionLevel
		*out = new(ProtectionLevel)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SigningKeySpec.
func (in *SigningKeySpec) DeepCopy() *SigningKeySpec {
	if in == nil {
		return nil
	}
	out := new(SigningKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SigningKeyStatus) DeepCopyInto(out *SigningKeyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EncryptedKeyMaterial != nil {
		in, out := &in.EncryptedKeyMaterial, &out.EncryptedKeyMaterial
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.PublicKey != nil {
		in, out := &in.PublicKey, &out.PublicKey
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SigningKeyStatus.
func (in *SigningKeyStatus) DeepCopy() *SigningKeyStatus {
	if in == nil {
		return nil
	}
	out := new(SigningKeyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThalesLunaHSMConfig) DeepCopyInto(out *ThalesLunaHSMConfig) {
	*out = *in
	if in.OrgHSMRefs != nil {
		in, out := &in.OrgHSMRefs, &out.OrgHSMRefs
		*out = make([]NamespacedReference, len(*in))
		copy(*out, *in)
	}
	out.Credentials = in.Credentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThalesLunaHSMConfig.
func (in *ThalesLunaHSMConfig) DeepCopy() *ThalesLunaHSMConfig {
	if in == nil {
		return nil
	}
	out := new(ThalesLunaHSMConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThalesLunaHSMStatus) DeepCopyInto(out *ThalesLunaHSMStatus) {
	*out = *in
	if in.ActiveMembers != nil {
		in, out := &in.ActiveMembers, &out.ActiveMembers
		*out = make([]LunaHAGroupMember, len(*in))
		copy(*out, *in)
	}
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(NamespacedReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThalesLunaHSMStatus.
func (in *ThalesLunaHSMStatus) DeepCopy() *ThalesLunaHSMStatus {
	if in == nil {
		return nil
	}
	out := new(ThalesLunaHSMStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WrappedKey) DeepCopyInto(out *WrappedKey) {
	*out = *in
	out.Metadata = in.Metadata
	if in.KeyMaterial != nil {
		in, out := &in.KeyMaterial, &out.KeyMaterial
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WrappedKey.
func (in *WrappedKey) DeepCopy() *WrappedKey {
	if in == nil {
		return nil
	}
	out := new(WrappedKey)
	in.DeepCopyInto(out)
	return out
}
