// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminUserSpec) DeepCopyInto(out *AdminUserSpec) {
	*out = *in
	if in.PasswordRef != nil {
		in, out := &in.PasswordRef, &out.PasswordRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminUserSpec.
func (in *AdminUserSpec) DeepCopy() *AdminUserSpec {
	if in == nil {
		return nil
	}
	out := new(AdminUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditLogSyslogTargetSpec) DeepCopyInto(out *AuditLogSyslogTargetSpec) {
	*out = *in
	if in.CertsSecretRef != nil {
		in, out := &in.CertsSecretRef, &out.CertsSecretRef
		*out = new(corev1.SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditLogSyslogTargetSpec.
func (in *AuditLogSyslogTargetSpec) DeepCopy() *AuditLogSyslogTargetSpec {
	if in == nil {
		return nil
	}
	out := new(AuditLogSyslogTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditLogTargetSpec) DeepCopyInto(out *AuditLogTargetSpec) {
	*out = *in
	if in.Syslog != nil {
		in, out := &in.Syslog, &out.Syslog
		*out = new(AuditLogSyslogTargetSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditLogTargetSpec.
func (in *AuditLogTargetSpec) DeepCopy() *AuditLogTargetSpec {
	if in == nil {
		return nil
	}
	out := new(AuditLogTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificatePrivateKey) DeepCopyInto(out *CertificatePrivateKey) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificatePrivateKey.
func (in *CertificatePrivateKey) DeepCopy() *CertificatePrivateKey {
	if in == nil {
		return nil
	}
	out := new(CertificatePrivateKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateRequest) DeepCopyInto(out *CertificateRequest) {
	*out = *in
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.RenewBefore != nil {
		in, out := &in.RenewBefore, &out.RenewBefore
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.PrivateKey != nil {
		in, out := &in.PrivateKey, &out.PrivateKey
		*out = new(CertificatePrivateKey)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateRequest.
func (in *CertificateRequest) DeepCopy() *CertificateRequest {
	if in == nil {
		return nil
	}
	out := new(CertificateRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClonedDBClusterConfig) DeepCopyInto(out *ClonedDBClusterConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClonedDBClusterConfig.
func (in *ClonedDBClusterConfig) DeepCopy() *ClonedDBClusterConfig {
	if in == nil {
		return nil
	}
	out := new(ClonedDBClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonExportSpec) DeepCopyInto(out *CommonExportSpec) {
	*out = *in
	if in.ExportLocation != nil {
		in, out := &in.ExportLocation, &out.ExportLocation
		*out = new(StorageSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonExportSpec.
func (in *CommonExportSpec) DeepCopy() *CommonExportSpec {
	if in == nil {
		return nil
	}
	out := new(CommonExportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonImportSpec) DeepCopyInto(out *CommonImportSpec) {
	*out = *in
	if in.DumpStorage != nil {
		in, out := &in.DumpStorage, &out.DumpStorage
		*out = new(StorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.LogStorage != nil {
		in, out := &in.LogStorage, &out.LogStorage
		*out = new(StorageSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonImportSpec.
func (in *CommonImportSpec) DeepCopy() *CommonImportSpec {
	if in == nil {
		return nil
	}
	out := new(CommonImportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Connectivity) DeepCopyInto(out *Connectivity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Connectivity.
func (in *Connectivity) DeepCopy() *Connectivity {
	if in == nil {
		return nil
	}
	out := new(Connectivity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CriticalIncident) DeepCopyInto(out *CriticalIncident) {
	*out = *in
	out.Resource = in.Resource
	if in.StackTrace != nil {
		in, out := &in.StackTrace, &out.StackTrace
		*out = make([]CriticalIncidentStackTraceMessage, len(*in))
		copy(*out, *in)
	}
	if in.MessageTemplateParams != nil {
		in, out := &in.MessageTemplateParams, &out.MessageTemplateParams
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = (*in).DeepCopy()
	}
	if in.TransientUntil != nil {
		in, out := &in.TransientUntil, &out.TransientUntil
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CriticalIncident.
func (in *CriticalIncident) DeepCopy() *CriticalIncident {
	if in == nil {
		return nil
	}
	out := new(CriticalIncident)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBLoadBalancerOptions) DeepCopyInto(out *DBLoadBalancerOptions) {
	*out = *in
	if in.GCP != nil {
		in, out := &in.GCP, &out.GCP
		*out = new(DBLoadBalancerOptionsGCP)
		**out = **in
	}
	if in.OnPrem != nil {
		in, out := &in.OnPrem, &out.OnPrem
		*out = new(DBLoadBalancerOptionsOnPrem)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBLoadBalancerOptions.
func (in *DBLoadBalancerOptions) DeepCopy() *DBLoadBalancerOptions {
	if in == nil {
		return nil
	}
	out := new(DBLoadBalancerOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataPlaneCertificateRequest) DeepCopyInto(out *DataPlaneCertificateRequest) {
	*out = *in
	in.CertificateRequest.DeepCopyInto(&out.CertificateRequest)
	if in.DNSNames != nil {
		in, out := &in.DNSNames, &out.DNSNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataPlaneCertificateRequest.
func (in *DataPlaneCertificateRequest) DeepCopy() *DataPlaneCertificateRequest {
	if in == nil {
		return nil
	}
	out := new(DataPlaneCertificateRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskSpec) DeepCopyInto(out *DiskSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]corev1.PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.DataSource != nil {
		in, out := &in.DataSource, &out.DataSource
		*out = new(corev1.TypedLocalObjectReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskSpec.
func (in *DiskSpec) DeepCopy() *DiskSpec {
	if in == nil {
		return nil
	}
	out := new(DiskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityStatus) DeepCopyInto(out *EntityStatus) {
	*out = *in
	if in.CriticalIncidents != nil {
		in, out := &in.CriticalIncidents, &out.CriticalIncidents
		*out = make([]CriticalIncident, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityStatus.
func (in *EntityStatus) DeepCopy() *EntityStatus {
	if in == nil {
		return nil
	}
	out := new(EntityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExportSpec) DeepCopyInto(out *ExportSpec) {
	*out = *in
	in.CommonExportSpec.DeepCopyInto(&out.CommonExportSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExportSpec.
func (in *ExportSpec) DeepCopy() *ExportSpec {
	if in == nil {
		return nil
	}
	out := new(ExportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExportStatus) DeepCopyInto(out *ExportStatus) {
	*out = *in
	in.EntityStatus.DeepCopyInto(&out.EntityStatus)
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompleteTime != nil {
		in, out := &in.CompleteTime, &out.CompleteTime
		*out = (*in).DeepCopy()
	}
	if in.ExportSubDirectory != nil {
		in, out := &in.ExportSubDirectory, &out.ExportSubDirectory
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExportStatus.
func (in *ExportStatus) DeepCopy() *ExportStatus {
	if in == nil {
		return nil
	}
	out := new(ExportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalServerSpec) DeepCopyInto(out *ExternalServerSpec) {
	*out = *in
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(corev1.SecretReference)
		**out = **in
	}
	if in.CertRef != nil {
		in, out := &in.CertRef, &out.CertRef
		*out = new(corev1.SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalServerSpec.
func (in *ExternalServerSpec) DeepCopy() *ExternalServerSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalServerStatus) DeepCopyInto(out *ExternalServerStatus) {
	*out = *in
	in.EntityStatus.DeepCopyInto(&out.EntityStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalServerStatus.
func (in *ExternalServerStatus) DeepCopy() *ExternalServerStatus {
	if in == nil {
		return nil
	}
	out := new(ExternalServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCSOptions) DeepCopyInto(out *GCSOptions) {
	*out = *in
	if in.Bucket != nil {
		in, out := &in.Bucket, &out.Bucket
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCSOptions.
func (in *GCSOptions) DeepCopy() *GCSOptions {
	if in == nil {
		return nil
	}
	out := new(GCSOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImportSpec) DeepCopyInto(out *ImportSpec) {
	*out = *in
	in.CommonImportSpec.DeepCopyInto(&out.CommonImportSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImportSpec.
func (in *ImportSpec) DeepCopy() *ImportSpec {
	if in == nil {
		return nil
	}
	out := new(ImportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImportStatus) DeepCopyInto(out *ImportStatus) {
	*out = *in
	in.EntityStatus.DeepCopyInto(&out.EntityStatus)
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompleteTime != nil {
		in, out := &in.CompleteTime, &out.CompleteTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImportStatus.
func (in *ImportStatus) DeepCopy() *ImportStatus {
	if in == nil {
		return nil
	}
	out := new(ImportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceBackupPlanSpec) DeepCopyInto(out *InstanceBackupPlanSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceBackupPlanSpec.
func (in *InstanceBackupPlanSpec) DeepCopy() *InstanceBackupPlanSpec {
	if in == nil {
		return nil
	}
	out := new(InstanceBackupPlanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceBackupPlanStatus) DeepCopyInto(out *InstanceBackupPlanStatus) {
	*out = *in
	in.EntityStatus.DeepCopyInto(&out.EntityStatus)
	in.LastBackupTime.DeepCopyInto(&out.LastBackupTime)
	in.NextBackupTime.DeepCopyInto(&out.NextBackupTime)
	if in.RecoveryWindow != nil {
		in, out := &in.RecoveryWindow, &out.RecoveryWindow
		*out = new(TimeWindow)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceBackupPlanStatus.
func (in *InstanceBackupPlanStatus) DeepCopy() *InstanceBackupPlanStatus {
	if in == nil {
		return nil
	}
	out := new(InstanceBackupPlanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceBackupSpec) DeepCopyInto(out *InstanceBackupSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceBackupSpec.
func (in *InstanceBackupSpec) DeepCopy() *InstanceBackupSpec {
	if in == nil {
		return nil
	}
	out := new(InstanceBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceBackupStatus) DeepCopyInto(out *InstanceBackupStatus) {
	*out = *in
	in.EntityStatus.DeepCopyInto(&out.EntityStatus)
	if in.CompleteTime != nil {
		in, out := &in.CompleteTime, &out.CompleteTime
		*out = (*in).DeepCopy()
	}
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceBackupStatus.
func (in *InstanceBackupStatus) DeepCopy() *InstanceBackupStatus {
	if in == nil {
		return nil
	}
	out := new(InstanceBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceComponentSpec) DeepCopyInto(out *InstanceComponentSpec) {
	*out = *in
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.UpgradeScheduledAt != nil {
		in, out := &in.UpgradeScheduledAt, &out.UpgradeScheduledAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceComponentSpec.
func (in *InstanceComponentSpec) DeepCopy() *InstanceComponentSpec {
	if in == nil {
		return nil
	}
	out := new(InstanceComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceComponentStatus) DeepCopyInto(out *InstanceComponentStatus) {
	*out = *in
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.UpgradeScheduledAt != nil {
		in, out := &in.UpgradeScheduledAt, &out.UpgradeScheduledAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceComponentStatus.
func (in *InstanceComponentStatus) DeepCopy() *InstanceComponentStatus {
	if in == nil {
		return nil
	}
	out := new(InstanceComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceHealthStatus) DeepCopyInto(out *InstanceHealthStatus) {
	*out = *in
	in.EntityStatus.DeepCopyInto(&out.EntityStatus)
	if in.LastHealthcheckRunTime != nil {
		in, out := &in.LastHealthcheckRunTime, &out.LastHealthcheckRunTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceHealthStatus.
func (in *InstanceHealthStatus) DeepCopy() *InstanceHealthStatus {
	if in == nil {
		return nil
	}
	out := new(InstanceHealthStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceRestoreSpec) DeepCopyInto(out *InstanceRestoreSpec) {
	*out = *in
	if in.PointInTime != nil {
		in, out := &in.PointInTime, &out.PointInTime
		*out = (*in).DeepCopy()
	}
	if in.ClonedDBClusterConfig != nil {
		in, out := &in.ClonedDBClusterConfig, &out.ClonedDBClusterConfig
		*out = new(ClonedDBClusterConfig)
		**out = **in
	}
	if in.RestoreStrategy != nil {
		in, out := &in.RestoreStrategy, &out.RestoreStrategy
		*out = new(RestoreStrategy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceRestoreSpec.
func (in *InstanceRestoreSpec) DeepCopy() *InstanceRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(InstanceRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceRestoreStatus) DeepCopyInto(out *InstanceRestoreStatus) {
	*out = *in
	in.EntityStatus.DeepCopyInto(&out.EntityStatus)
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = (*in).DeepCopy()
	}
	if in.CompleteTime != nil {
		in, out := &in.CompleteTime, &out.CompleteTime
		*out = (*in).DeepCopy()
	}
	if in.RestoredPointInTime != nil {
		in, out := &in.RestoredPointInTime, &out.RestoredPointInTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceRestoreStatus.
func (in *InstanceRestoreStatus) DeepCopy() *InstanceRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(InstanceRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceSpec) DeepCopyInto(out *InstanceSpec) {
	*out = *in
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make(map[InstanceComponentName]InstanceComponentSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.DBLoadBalancerOptions != nil {
		in, out := &in.DBLoadBalancerOptions, &out.DBLoadBalancerOptions
		*out = new(DBLoadBalancerOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.SourceCidrRanges != nil {
		in, out := &in.SourceCidrRanges, &out.SourceCidrRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make(map[Service]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(Resource)
		(*in).DeepCopyInto(*out)
	}
	if in.DatabasePatchingTimeout != nil {
		in, out := &in.DatabasePatchingTimeout, &out.DatabasePatchingTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.AdminUser != nil {
		in, out := &in.AdminUser, &out.AdminUser
		*out = new(AdminUserSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SystemUserPasswordRefs != nil {
		in, out := &in.SystemUserPasswordRefs, &out.SystemUserPasswordRefs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.IsStopped != nil {
		in, out := &in.IsStopped, &out.IsStopped
		*out = new(bool)
		**out = **in
	}
	if in.AvailabilityOptions != nil {
		in, out := &in.AvailabilityOptions, &out.AvailabilityOptions
		*out = new(AvailabilityOptions)
		**out = **in
	}
	if in.AuditLogTarget != nil {
		in, out := &in.AuditLogTarget, &out.AuditLogTarget
		*out = new(AuditLogTargetSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Replication != nil {
		in, out := &in.Replication, &out.Replication
		*out = new(ReplicationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SchedulingConfig != nil {
		in, out := &in.SchedulingConfig, &out.SchedulingConfig
		*out = new(SchedulingConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceSpec.
func (in *InstanceSpec) DeepCopy() *InstanceSpec {
	if in == nil {
		return nil
	}
	out := new(InstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceStatus) DeepCopyInto(out *InstanceStatus) {
	*out = *in
	in.EntityStatus.DeepCopyInto(&out.EntityStatus)
	if in.RestoredFrom != nil {
		in, out := &in.RestoredFrom, &out.RestoredFrom
		*out = new(RestoredFrom)
		(*in).DeepCopyInto(*out)
	}
	if in.CurrentParameters != nil {
		in, out := &in.CurrentParameters, &out.CurrentParameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LastFailedParameterUpdate != nil {
		in, out := &in.LastFailedParameterUpdate, &out.LastFailedParameterUpdate
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ExternalConnectivity != nil {
		in, out := &in.ExternalConnectivity, &out.ExternalConnectivity
		*out = new(Connectivity)
		**out = **in
	}
	if in.InternalConnectivity != nil {
		in, out := &in.InternalConnectivity, &out.InternalConnectivity
		*out = new(Connectivity)
		**out = **in
	}
	if in.ActiveImages != nil {
		in, out := &in.ActiveImages, &out.ActiveImages
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LastFailedImages != nil {
		in, out := &in.LastFailedImages, &out.LastFailedImages
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ActiveComponents != nil {
		in, out := &in.ActiveComponents, &out.ActiveComponents
		*out = make(map[InstanceComponentName]InstanceComponentStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ReplicationStatus != nil {
		in, out := &in.ReplicationStatus, &out.ReplicationStatus
		*out = new(ReplicationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.AllocatedResources != nil {
		in, out := &in.AllocatedResources, &out.AllocatedResources
		*out = new(Resource)
		(*in).DeepCopyInto(*out)
	}
	if in.WalArchiveSetting != nil {
		in, out := &in.WalArchiveSetting, &out.WalArchiveSetting
		*out = new(WalArchiveStatus)
		**out = **in
	}
	if in.AdminUser != nil {
		in, out := &in.AdminUser, &out.AdminUser
		*out = new(AdminUserStatus)
		**out = **in
	}
	if in.AlloyDbAdminUser != nil {
		in, out := &in.AlloyDbAdminUser, &out.AlloyDbAdminUser
		*out = new(AdminUserStatus)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeManager != nil {
		in, out := &in.NodeManager, &out.NodeManager
		*out = new(NodeManagerStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceStatus.
func (in *InstanceStatus) DeepCopy() *InstanceStatus {
	if in == nil {
		return nil
	}
	out := new(InstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceSwitchoverSpec) DeepCopyInto(out *InstanceSwitchoverSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceSwitchoverSpec.
func (in *InstanceSwitchoverSpec) DeepCopy() *InstanceSwitchoverSpec {
	if in == nil {
		return nil
	}
	out := new(InstanceSwitchoverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceSwitchoverStatus) DeepCopyInto(out *InstanceSwitchoverStatus) {
	*out = *in
	in.EntityStatus.DeepCopyInto(&out.EntityStatus)
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = (*in).DeepCopy()
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	out.Internal = in.Internal
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceSwitchoverStatus.
func (in *InstanceSwitchoverStatus) DeepCopy() *InstanceSwitchoverStatus {
	if in == nil {
		return nil
	}
	out := new(InstanceSwitchoverStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LSN) DeepCopyInto(out *LSN) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LSN.
func (in *LSN) DeepCopy() *LSN {
	if in == nil {
		return nil
	}
	out := new(LSN)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeManagerStatus) DeepCopyInto(out *NodeManagerStatus) {
	*out = *in
	if in.SystemUsers != nil {
		in, out := &in.SystemUsers, &out.SystemUsers
		*out = make(map[string]NodeManagerSystemUserStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeManagerStatus.
func (in *NodeManagerStatus) DeepCopy() *NodeManagerStatus {
	if in == nil {
		return nil
	}
	out := new(NodeManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeManagerSystemUserStatus) DeepCopyInto(out *NodeManagerSystemUserStatus) {
	*out = *in
	in.PasswordUpdatedAt.DeepCopyInto(&out.PasswordUpdatedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeManagerSystemUserStatus.
func (in *NodeManagerSystemUserStatus) DeepCopy() *NodeManagerSystemUserStatus {
	if in == nil {
		return nil
	}
	out := new(NodeManagerSystemUserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniSvcInstanceBackupPlanSpec) DeepCopyInto(out *OmniSvcInstanceBackupPlanSpec) {
	*out = *in
	if in.BackupLocation != nil {
		in, out := &in.BackupLocation, &out.BackupLocation
		*out = new(StorageSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniSvcInstanceBackupPlanSpec.
func (in *OmniSvcInstanceBackupPlanSpec) DeepCopy() *OmniSvcInstanceBackupPlanSpec {
	if in == nil {
		return nil
	}
	out := new(OmniSvcInstanceBackupPlanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniSvcInstanceBackupSpec) DeepCopyInto(out *OmniSvcInstanceBackupSpec) {
	*out = *in
	out.PhysicalBackupSpec = in.PhysicalBackupSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniSvcInstanceBackupSpec.
func (in *OmniSvcInstanceBackupSpec) DeepCopy() *OmniSvcInstanceBackupSpec {
	if in == nil {
		return nil
	}
	out := new(OmniSvcInstanceBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniSvcInstanceBackupStatus) DeepCopyInto(out *OmniSvcInstanceBackupStatus) {
	*out = *in
	in.PhysicalBackupStatus.DeepCopyInto(&out.PhysicalBackupStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniSvcInstanceBackupStatus.
func (in *OmniSvcInstanceBackupStatus) DeepCopy() *OmniSvcInstanceBackupStatus {
	if in == nil {
		return nil
	}
	out := new(OmniSvcInstanceBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PGBaseBackupStrategy) DeepCopyInto(out *PGBaseBackupStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PGBaseBackupStrategy.
func (in *PGBaseBackupStrategy) DeepCopy() *PGBaseBackupStrategy {
	if in == nil {
		return nil
	}
	out := new(PGBaseBackupStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PGRewindStrategy) DeepCopyInto(out *PGRewindStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PGRewindStrategy.
func (in *PGRewindStrategy) DeepCopy() *PGRewindStrategy {
	if in == nil {
		return nil
	}
	out := new(PGRewindStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgBouncerSpec) DeepCopyInto(out *PgBouncerSpec) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ServerTLS != nil {
		in, out := &in.ServerTLS, &out.ServerTLS
		*out = new(ServerTLSSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgBouncerSpec.
func (in *PgBouncerSpec) DeepCopy() *PgBouncerSpec {
	if in == nil {
		return nil
	}
	out := new(PgBouncerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgBouncerStatus) DeepCopyInto(out *PgBouncerStatus) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]Endpoint, len(*in))
		copy(*out, *in)
	}
	in.EntityStatus.DeepCopyInto(&out.EntityStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgBouncerStatus.
func (in *PgBouncerStatus) DeepCopy() *PgBouncerStatus {
	if in == nil {
		return nil
	}
	out := new(PgBouncerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhysicalBackupSpec) DeepCopyInto(out *PhysicalBackupSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhysicalBackupSpec.
func (in *PhysicalBackupSpec) DeepCopy() *PhysicalBackupSpec {
	if in == nil {
		return nil
	}
	out := new(PhysicalBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhysicalBackupStatus) DeepCopyInto(out *PhysicalBackupStatus) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	in.EndTime.DeepCopyInto(&out.EndTime)
	out.WAL = in.WAL
	out.LSN = in.LSN
	in.Size.DeepCopyInto(&out.Size)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhysicalBackupStatus.
func (in *PhysicalBackupStatus) DeepCopy() *PhysicalBackupStatus {
	if in == nil {
		return nil
	}
	out := new(PhysicalBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhysicalReplicationSetupStrategy) DeepCopyInto(out *PhysicalReplicationSetupStrategy) {
	*out = *in
	if in.PGBaseBackup != nil {
		in, out := &in.PGBaseBackup, &out.PGBaseBackup
		*out = new(PGBaseBackupStrategy)
		**out = **in
	}
	if in.PGRewind != nil {
		in, out := &in.PGRewind, &out.PGRewind
		*out = new(PGRewindStrategy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhysicalReplicationSetupStrategy.
func (in *PhysicalReplicationSetupStrategy) DeepCopy() *PhysicalReplicationSetupStrategy {
	if in == nil {
		return nil
	}
	out := new(PhysicalReplicationSetupStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhysicalReplicationSetupStrategyStatus) DeepCopyInto(out *PhysicalReplicationSetupStrategyStatus) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	in.EndedAt.DeepCopyInto(&out.EndedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhysicalReplicationSetupStrategyStatus.
func (in *PhysicalReplicationSetupStrategyStatus) DeepCopy() *PhysicalReplicationSetupStrategyStatus {
	if in == nil {
		return nil
	}
	out := new(PhysicalReplicationSetupStrategyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationConfigSpec) DeepCopyInto(out *ReplicationConfigSpec) {
	*out = *in
	in.Parent.DeepCopyInto(&out.Parent)
	if in.PhysicalUpstream != nil {
		in, out := &in.PhysicalUpstream, &out.PhysicalUpstream
		*out = new(ReplicationPhysicalUpstreamSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.LogicalUpstream != nil {
		in, out := &in.LogicalUpstream, &out.LogicalUpstream
		*out = new(ReplicationLogicalUpstreamSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PhysicalDownstream != nil {
		in, out := &in.PhysicalDownstream, &out.PhysicalDownstream
		*out = new(ReplicationPhysicalDownstreamSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationConfigSpec.
func (in *ReplicationConfigSpec) DeepCopy() *ReplicationConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ReplicationConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationConfigStatus) DeepCopyInto(out *ReplicationConfigStatus) {
	*out = *in
	in.EntityStatus.DeepCopyInto(&out.EntityStatus)
	if in.PhysicalUpstream != nil {
		in, out := &in.PhysicalUpstream, &out.PhysicalUpstream
		*out = new(ReplicationPhysicalUpstreamStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.PhysicalDownstream != nil {
		in, out := &in.PhysicalDownstream, &out.PhysicalDownstream
		*out = new(ReplicationPhysicalDownstreamStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LogicalUpstream != nil {
		in, out := &in.LogicalUpstream, &out.LogicalUpstream
		*out = new(ReplicationLogicalUpstreamStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationConfigStatus.
func (in *ReplicationConfigStatus) DeepCopy() *ReplicationConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicationConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationDatabase) DeepCopyInto(out *ReplicationDatabase) {
	*out = *in
	if in.DBNode != nil {
		in, out := &in.DBNode, &out.DBNode
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationDatabase.
func (in *ReplicationDatabase) DeepCopy() *ReplicationDatabase {
	if in == nil {
		return nil
	}
	out := new(ReplicationDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationLogicalUpstreamSpec) DeepCopyInto(out *ReplicationLogicalUpstreamSpec) {
	*out = *in
	in.ReplicationUpstreamUserSpec.DeepCopyInto(&out.ReplicationUpstreamUserSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationLogicalUpstreamSpec.
func (in *ReplicationLogicalUpstreamSpec) DeepCopy() *ReplicationLogicalUpstreamSpec {
	if in == nil {
		return nil
	}
	out := new(ReplicationLogicalUpstreamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationLogicalUpstreamStatus) DeepCopyInto(out *ReplicationLogicalUpstreamStatus) {
	*out = *in
	in.ReplicationUpstreamStatus.DeepCopyInto(&out.ReplicationUpstreamStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationLogicalUpstreamStatus.
func (in *ReplicationLogicalUpstreamStatus) DeepCopy() *ReplicationLogicalUpstreamStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicationLogicalUpstreamStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationPhysicalDownstreamSpec) DeepCopyInto(out *ReplicationPhysicalDownstreamSpec) {
	*out = *in
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(corev1.SecretReference)
		**out = **in
	}
	if in.SetupStrategies != nil {
		in, out := &in.SetupStrategies, &out.SetupStrategies
		*out = make([]PhysicalReplicationSetupStrategy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RerunSetupAt != nil {
		in, out := &in.RerunSetupAt, &out.RerunSetupAt
		*out = (*in).DeepCopy()
	}
	if in.InvalidateSyncStatusAt != nil {
		in, out := &in.InvalidateSyncStatusAt, &out.InvalidateSyncStatusAt
		*out = (*in).DeepCopy()
	}
	if in.ReplicationSlotsAllowList != nil {
		in, out := &in.ReplicationSlotsAllowList, &out.ReplicationSlotsAllowList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationPhysicalDownstreamSpec.
func (in *ReplicationPhysicalDownstreamSpec) DeepCopy() *ReplicationPhysicalDownstreamSpec {
	if in == nil {
		return nil
	}
	out := new(ReplicationPhysicalDownstreamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationPhysicalDownstreamStatus) DeepCopyInto(out *ReplicationPhysicalDownstreamStatus) {
	*out = *in
	if in.SetupStrategies != nil {
		in, out := &in.SetupStrategies, &out.SetupStrategies
		*out = make([]PhysicalReplicationSetupStrategyStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationPhysicalDownstreamStatus.
func (in *ReplicationPhysicalDownstreamStatus) DeepCopy() *ReplicationPhysicalDownstreamStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicationPhysicalDownstreamStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationPhysicalUpstreamSpec) DeepCopyInto(out *ReplicationPhysicalUpstreamSpec) {
	*out = *in
	in.ReplicationUpstreamUserSpec.DeepCopyInto(&out.ReplicationUpstreamUserSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationPhysicalUpstreamSpec.
func (in *ReplicationPhysicalUpstreamSpec) DeepCopy() *ReplicationPhysicalUpstreamSpec {
	if in == nil {
		return nil
	}
	out := new(ReplicationPhysicalUpstreamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationPhysicalUpstreamStatus) DeepCopyInto(out *ReplicationPhysicalUpstreamStatus) {
	*out = *in
	in.ReplicationUpstreamStatus.DeepCopyInto(&out.ReplicationUpstreamStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationPhysicalUpstreamStatus.
func (in *ReplicationPhysicalUpstreamStatus) DeepCopy() *ReplicationPhysicalUpstreamStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicationPhysicalUpstreamStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationProfileSpec) DeepCopyInto(out *ReplicationProfileSpec) {
	*out = *in
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(corev1.SecretReference)
		**out = **in
	}
	if in.CertificateReference != nil {
		in, out := &in.CertificateReference, &out.CertificateReference
		*out = new(CertificateRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationProfileSpec.
func (in *ReplicationProfileSpec) DeepCopy() *ReplicationProfileSpec {
	if in == nil {
		return nil
	}
	out := new(ReplicationProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationProfileStatus) DeepCopyInto(out *ReplicationProfileStatus) {
	*out = *in
	in.EntityStatus.DeepCopyInto(&out.EntityStatus)
	in.ReplicationProfileSpec.DeepCopyInto(&out.ReplicationProfileSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationProfileStatus.
func (in *ReplicationProfileStatus) DeepCopy() *ReplicationProfileStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicationProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationSpec) DeepCopyInto(out *ReplicationSpec) {
	*out = *in
	if in.Profiles != nil {
		in, out := &in.Profiles, &out.Profiles
		*out = make([]ReplicationProfileSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationSpec.
func (in *ReplicationSpec) DeepCopy() *ReplicationSpec {
	if in == nil {
		return nil
	}
	out := new(ReplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationStatus) DeepCopyInto(out *ReplicationStatus) {
	*out = *in
	in.EntityStatus.DeepCopyInto(&out.EntityStatus)
	if in.Profiles != nil {
		in, out := &in.Profiles, &out.Profiles
		*out = make([]ReplicationProfileStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationStatus.
func (in *ReplicationStatus) DeepCopy() *ReplicationStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationUpstreamStatus) DeepCopyInto(out *ReplicationUpstreamStatus) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationUpstreamStatus.
func (in *ReplicationUpstreamStatus) DeepCopy() *ReplicationUpstreamStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicationUpstreamStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationUpstreamUserSpec) DeepCopyInto(out *ReplicationUpstreamUserSpec) {
	*out = *in
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(corev1.SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationUpstreamUserSpec.
func (in *ReplicationUpstreamUserSpec) DeepCopy() *ReplicationUpstreamUserSpec {
	if in == nil {
		return nil
	}
	out := new(ReplicationUpstreamUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resource) DeepCopyInto(out *Resource) {
	*out = *in
	out.Memory = in.Memory.DeepCopy()
	out.Cpu = in.Cpu.DeepCopy()
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int32)
		**out = **in
	}
	if in.Disks != nil {
		in, out := &in.Disks, &out.Disks
		*out = make([]DiskSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(ResourceList)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resource.
func (in *Resource) DeepCopy() *Resource {
	if in == nil {
		return nil
	}
	out := new(Resource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceList) DeepCopyInto(out *ResourceList) {
	*out = *in
	out.Memory = in.Memory.DeepCopy()
	out.Cpu = in.Cpu.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceList.
func (in *ResourceList) DeepCopy() *ResourceList {
	if in == nil {
		return nil
	}
	out := new(ResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoredFrom) DeepCopyInto(out *RestoredFrom) {
	*out = *in
	if in.RestoredTime != nil {
		in, out := &in.RestoredTime, &out.RestoredTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoredFrom.
func (in *RestoredFrom) DeepCopy() *RestoredFrom {
	if in == nil {
		return nil
	}
	out := new(RestoredFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Options) DeepCopyInto(out *S3Options) {
	*out = *in
	if in.Bucket != nil {
		in, out := &in.Bucket, &out.Bucket
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	out.SecretRef = in.SecretRef
	out.CertRef = in.CertRef
	if in.CABundle != nil {
		in, out := &in.CABundle, &out.CABundle
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Options.
func (in *S3Options) DeepCopy() *S3Options {
	if in == nil {
		return nil
	}
	out := new(S3Options)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingConfig) DeepCopyInto(out *SchedulingConfig) {
	*out = *in
	if in.NodeAffinity != nil {
		in, out := &in.NodeAffinity, &out.NodeAffinity
		*out = new(corev1.NodeAffinity)
		(*in).DeepCopyInto(*out)
	}
	if in.PodAffinity != nil {
		in, out := &in.PodAffinity, &out.PodAffinity
		*out = new(corev1.PodAffinity)
		(*in).DeepCopyInto(*out)
	}
	if in.PodAntiAffinity != nil {
		in, out := &in.PodAntiAffinity, &out.PodAntiAffinity
		*out = new(corev1.PodAntiAffinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]corev1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingConfig.
func (in *SchedulingConfig) DeepCopy() *SchedulingConfig {
	if in == nil {
		return nil
	}
	out := new(SchedulingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerTLSSpec) DeepCopyInto(out *ServerTLSSpec) {
	*out = *in
	if in.CertSecret != nil {
		in, out := &in.CertSecret, &out.CertSecret
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerTLSSpec.
func (in *ServerTLSSpec) DeepCopy() *ServerTLSSpec {
	if in == nil {
		return nil
	}
	out := new(ServerTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SidecarSpec) DeepCopyInto(out *SidecarSpec) {
	*out = *in
	if in.Sidecars != nil {
		in, out := &in.Sidecars, &out.Sidecars
		*out = make([]corev1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AdditionalVolumes != nil {
		in, out := &in.AdditionalVolumes, &out.AdditionalVolumes
		*out = make([]corev1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SidecarSpec.
func (in *SidecarSpec) DeepCopy() *SidecarSpec {
	if in == nil {
		return nil
	}
	out := new(SidecarSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Size) DeepCopyInto(out *Size) {
	*out = *in
	out.DatabaseSize = in.DatabaseSize.DeepCopy()
	out.DatabaseBackupSize = in.DatabaseBackupSize.DeepCopy()
	out.BackupSize = in.BackupSize.DeepCopy()
	out.BackupSetSize = in.BackupSetSize.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Size.
func (in *Size) DeepCopy() *Size {
	if in == nil {
		return nil
	}
	out := new(Size)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	if in.S3Options != nil {
		in, out := &in.S3Options, &out.S3Options
		*out = new(S3Options)
		(*in).DeepCopyInto(*out)
	}
	if in.GCSOptions != nil {
		in, out := &in.GCSOptions, &out.GCSOptions
		*out = new(GCSOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSSpec) DeepCopyInto(out *TLSSpec) {
	*out = *in
	if in.CertSecret != nil {
		in, out := &in.CertSecret, &out.CertSecret
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.DataPlaneCertIssuer != nil {
		in, out := &in.DataPlaneCertIssuer, &out.DataPlaneCertIssuer
		*out = new(IssuerReference)
		**out = **in
	}
	if in.ControlPlaneAgentsCertIssuer != nil {
		in, out := &in.ControlPlaneAgentsCertIssuer, &out.ControlPlaneAgentsCertIssuer
		*out = new(IssuerReference)
		**out = **in
	}
	if in.DataPlaneCertRequest != nil {
		in, out := &in.DataPlaneCertRequest, &out.DataPlaneCertRequest
		*out = new(DataPlaneCertificateRequest)
		(*in).DeepCopyInto(*out)
	}
	if in.ControlPlaneAgentsCertRequest != nil {
		in, out := &in.ControlPlaneAgentsCertRequest, &out.ControlPlaneAgentsCertRequest
		*out = new(CertificateRequest)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSSpec.
func (in *TLSSpec) DeepCopy() *TLSSpec {
	if in == nil {
		return nil
	}
	out := new(TLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSStatus) DeepCopyInto(out *TLSStatus) {
	*out = *in
	if in.CertSecret != nil {
		in, out := &in.CertSecret, &out.CertSecret
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.ControlPlaneAgentsCertIssuer != nil {
		in, out := &in.ControlPlaneAgentsCertIssuer, &out.ControlPlaneAgentsCertIssuer
		*out = new(IssuerReference)
		**out = **in
	}
	if in.ControlPlaneAgentsCertRequest != nil {
		in, out := &in.ControlPlaneAgentsCertRequest, &out.ControlPlaneAgentsCertRequest
		*out = new(CertificateRequest)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSStatus.
func (in *TLSStatus) DeepCopy() *TLSStatus {
	if in == nil {
		return nil
	}
	out := new(TLSStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeWindow) DeepCopyInto(out *TimeWindow) {
	*out = *in
	if in.Begin != nil {
		in, out := &in.Begin, &out.Begin
		*out = (*in).DeepCopy()
	}
	if in.End != nil {
		in, out := &in.End, &out.End
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeWindow.
func (in *TimeWindow) DeepCopy() *TimeWindow {
	if in == nil {
		return nil
	}
	out := new(TimeWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WAL) DeepCopyInto(out *WAL) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WAL.
func (in *WAL) DeepCopy() *WAL {
	if in == nil {
		return nil
	}
	out := new(WAL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WalArchiveSpec) DeepCopyInto(out *WalArchiveSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WalArchiveSpec.
func (in *WalArchiveSpec) DeepCopy() *WalArchiveSpec {
	if in == nil {
		return nil
	}
	out := new(WalArchiveSpec)
	in.DeepCopyInto(out)
	return out
}
