load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")
load("//build/rules:global_api.bzl", "mux_api_package")
load("//build/rules/controller_gen:aspect.bzl", "kubebuilder_analyze")

# gazelle:exclude zz_generated.*.go

kubebuilder_analyze(
    name = "api_typedata",
    srcs = [
        "doc.go",
        "marketplaceservices_types.go",
        "marketplaceservicesreplica_types.go",
    ],
    importpath = "gke-internal.googlesource.com/private-cloud/pkg/apis/public/global/marketplace/v1",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/apis/common/global/v1alpha1",
        "//pkg/apis/core/v1alpha1",
        "//pkg/apis/public/resourcemanager/v1alpha1",
        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
    ],
)

mux_api_package(
    name = "api",
    mux_dep = "//pkg/apis/common/global/v1alpha1",
    mux_types = [
        "ServiceDescription",
        "ServiceVersion",
        "ServiceCatalog",
        "ServiceCatalogBinding",
    ],
    targets = [":api_typedata"],
)

kubebuilder_analyze(
    name = "replica_typedata",
    srcs = [
        "doc.go",
        "marketplaceservicesreplica_types.go",
    ],
    importpath = "gke-internal.googlesource.com/private-cloud/pkg/apis/public/global/marketplace/v1",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/apis/core/v1alpha1",
        "//pkg/apis/public/resourcemanager/v1alpha1",
        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
    ],
)

go_library(
    name = "marketplace",
    srcs = [
        "doc.go",
        "generated.deepcopy.go",  #keep
        "generated.mux.go",  #keep
        "groupversion_info.go",
        "marketplaceservices_types.go",
        "marketplaceservicesreplica_types.go",
    ],
    importpath = "gke-internal.googlesource.com/private-cloud/pkg/apis/public/global/marketplace/v1",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/apis/common/global/v1alpha1",
        "//pkg/apis/core/v1alpha1",
        "//pkg/apis/public/global",
        "//pkg/apis/public/resourcemanager/v1alpha1",
        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
        "//vendor/k8s.io/apimachinery/pkg/labels",
        "//vendor/k8s.io/apimachinery/pkg/runtime",  # keep
        "//vendor/k8s.io/apimachinery/pkg/runtime/schema",
        "//vendor/sigs.k8s.io/controller-runtime/pkg/scheme",
    ],
)

go_test(
    name = "marketplace_test",
    srcs = ["marketplaceservicesreplica_types_test.go"],
    embed = [":marketplace"],
    deps = [
        "//pkg/apis/public/resourcemanager/v1alpha1",
        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
    ],
)
