load("@aspect_bazel_lib//lib:write_source_files.bzl", "write_source_files")
load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("//build/rules/controller_gen:aspect.bzl", "kubebuilder_analyze")
load("//build/rules/controller_gen:kubebuilder.bzl", "deepcopygen")

# gazelle:exclude zz_generated.*.go

kubebuilder_analyze(
    name = "export_typedata",
    srcs = ["export_types.go"],
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/apis/public/dbs/enterprise/common",
        "//pkg/apis/public/dbs/omnicore/core/v1:core",
        "//vendor/k8s.io/apimachinery/pkg/runtime",
        "//vendor/sigs.k8s.io/controller-runtime/pkg/client",
    ],
)

deepcopygen(
    name = "export_deepcopy",
    targets = [":export_typedata"],
    visibility = ["//visibility:public"],
)

write_source_files(
    name = "export_deepcopy_copy",
    files = {
        "zz_generated.deepcopy.go": ":export_deepcopy",
    },
)

go_library(
    name = "export",
    srcs = [
        "export_types.go",
        "zz_generated.deepcopy.go",  # keep
    ],
    importpath = "gke-internal.googlesource.com/private-cloud/pkg/apis/public/dbs/enterprise/export/v1",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/apis/public/dbs/enterprise/common",
        "//pkg/apis/public/dbs/omnicore/core/v1:core",
        "//vendor/k8s.io/apimachinery/pkg/runtime",  # keep
        "//vendor/sigs.k8s.io/controller-runtime/pkg/client",
    ],
)
