load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "utils",
    srcs = [
        "common.go",
        "consts.go",
    ],
    importpath = "gke-internal.googlesource.com/private-cloud/pkg/apis/public/dbs/enterprise/common/utils",
    visibility = ["//visibility:public"],
    deps = ["//vendor/sigs.k8s.io/controller-runtime/pkg/client"],
)
