// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by bazel. DO NOT EDIT.

package v1

import (
	"gke-internal.googlesource.com/private-cloud/pkg/apis/common/global/v1alpha1"
)

var _ v1alpha1.MuxReplicaInterface = &ProjectReplica{}

func (r *ProjectReplica) GetSpec() any {
	return v1alpha1.NewTypedFieldAccessor(&r.Spec).GetField()
}

func (r *ProjectReplica) SetSpec(spec any) error {
	return v1alpha1.NewTypedFieldAccessor(&r.Spec).SetField(spec)
}

func (r *ProjectReplica) GetStatus() any {
	return v1alpha1.NewTypedFieldAccessor(&r.Status).GetField()
}

func (r *ProjectReplica) SetStatus(status any) error {
	return v1alpha1.NewTypedFieldAccessor(&r.Status).SetField(status)
}

var _ v1alpha1.MuxStatusInterface = &ProjectStatus{}

func (s *ProjectStatus) GetZones() v1alpha1.ListMap[string, v1alpha1.ZoneStatusInterface] {
	return v1alpha1.NewZoneStatusListAccessor(&s.Zones).GetZones()
}

func (s *ProjectStatus) SetZones(zones v1alpha1.ListMap[string, v1alpha1.ZoneStatusInterface]) error {
	return v1alpha1.NewZoneStatusListAccessor(&s.Zones).SetZones(zones)
}

var _ v1alpha1.ZoneStatusInterface = &ProjectZoneStatus{}

func (s *ProjectZoneStatus) GetReplicaStatus() any {
	return v1alpha1.NewTypedFieldAccessor(&s.ReplicaStatus).GetField()
}

func (s *ProjectZoneStatus) SetReplicaStatus(replicaStatus any) error {
	return v1alpha1.NewTypedFieldAccessor(&s.ReplicaStatus).SetField(replicaStatus)
}

var _ v1alpha1.MuxResourceInterface = &Project{}

func (r *Project) GetSpec() any {
	return v1alpha1.NewTypedFieldAccessor(&r.Spec).GetField()
}

func (r *Project) SetSpec(spec any) error {
	return v1alpha1.NewTypedFieldAccessor(&r.Spec).SetField(spec)
}

func (r *Project) GetStatus() v1alpha1.MuxStatusInterface {
	return v1alpha1.NewMuxStatusAccessor(&r.Status).GetStatus()
}

func (r *Project) SetStatus(status v1alpha1.MuxStatusInterface) error {
	return v1alpha1.NewMuxStatusAccessor(&r.Status).SetStatus(status)
}

var _ v1alpha1.MuxReplicaInterface = &ProjectServiceAccountReplica{}

func (r *ProjectServiceAccountReplica) GetSpec() any {
	return v1alpha1.NewTypedFieldAccessor(&r.Spec).GetField()
}

func (r *ProjectServiceAccountReplica) SetSpec(spec any) error {
	return v1alpha1.NewTypedFieldAccessor(&r.Spec).SetField(spec)
}

func (r *ProjectServiceAccountReplica) GetStatus() any {
	return v1alpha1.NewTypedFieldAccessor(&r.Status).GetField()
}

func (r *ProjectServiceAccountReplica) SetStatus(status any) error {
	return v1alpha1.NewTypedFieldAccessor(&r.Status).SetField(status)
}

var _ v1alpha1.MuxStatusInterface = &ProjectServiceAccountStatus{}

func (s *ProjectServiceAccountStatus) GetZones() v1alpha1.ListMap[string, v1alpha1.ZoneStatusInterface] {
	return v1alpha1.NewZoneStatusListAccessor(&s.Zones).GetZones()
}

func (s *ProjectServiceAccountStatus) SetZones(zones v1alpha1.ListMap[string, v1alpha1.ZoneStatusInterface]) error {
	return v1alpha1.NewZoneStatusListAccessor(&s.Zones).SetZones(zones)
}

var _ v1alpha1.ZoneStatusInterface = &ProjectServiceAccountZoneStatus{}

func (s *ProjectServiceAccountZoneStatus) GetReplicaStatus() any {
	return v1alpha1.NewTypedFieldAccessor(&s.ReplicaStatus).GetField()
}

func (s *ProjectServiceAccountZoneStatus) SetReplicaStatus(replicaStatus any) error {
	return v1alpha1.NewTypedFieldAccessor(&s.ReplicaStatus).SetField(replicaStatus)
}

var _ v1alpha1.MuxResourceInterface = &ProjectServiceAccount{}

func (r *ProjectServiceAccount) GetSpec() any {
	return v1alpha1.NewTypedFieldAccessor(&r.Spec).GetField()
}

func (r *ProjectServiceAccount) SetSpec(spec any) error {
	return v1alpha1.NewTypedFieldAccessor(&r.Spec).SetField(spec)
}

func (r *ProjectServiceAccount) GetStatus() v1alpha1.MuxStatusInterface {
	return v1alpha1.NewMuxStatusAccessor(&r.Status).GetStatus()
}

func (r *ProjectServiceAccount) SetStatus(status v1alpha1.MuxStatusInterface) error {
	return v1alpha1.NewMuxStatusAccessor(&r.Status).SetStatus(status)
}

var _ v1alpha1.MuxReplicaInterface = &TagKeyReplica{}

func (r *TagKeyReplica) GetSpec() any {
	return v1alpha1.NewTypedFieldAccessor(&r.Spec).GetField()
}

func (r *TagKeyReplica) SetSpec(spec any) error {
	return v1alpha1.NewTypedFieldAccessor(&r.Spec).SetField(spec)
}

func (r *TagKeyReplica) GetStatus() any {
	return v1alpha1.NewTypedFieldAccessor(&r.Status).GetField()
}

func (r *TagKeyReplica) SetStatus(status any) error {
	return v1alpha1.NewTypedFieldAccessor(&r.Status).SetField(status)
}

var _ v1alpha1.MuxStatusInterface = &TagKeyStatus{}

func (s *TagKeyStatus) GetZones() v1alpha1.ListMap[string, v1alpha1.ZoneStatusInterface] {
	return v1alpha1.NewZoneStatusListAccessor(&s.Zones).GetZones()
}

func (s *TagKeyStatus) SetZones(zones v1alpha1.ListMap[string, v1alpha1.ZoneStatusInterface]) error {
	return v1alpha1.NewZoneStatusListAccessor(&s.Zones).SetZones(zones)
}

var _ v1alpha1.ZoneStatusInterface = &TagKeyZoneStatus{}

func (s *TagKeyZoneStatus) GetReplicaStatus() any {
	return v1alpha1.NewTypedFieldAccessor(&s.ReplicaStatus).GetField()
}

func (s *TagKeyZoneStatus) SetReplicaStatus(replicaStatus any) error {
	return v1alpha1.NewTypedFieldAccessor(&s.ReplicaStatus).SetField(replicaStatus)
}

var _ v1alpha1.MuxResourceInterface = &TagKey{}

func (r *TagKey) GetSpec() any {
	return v1alpha1.NewTypedFieldAccessor(&r.Spec).GetField()
}

func (r *TagKey) SetSpec(spec any) error {
	return v1alpha1.NewTypedFieldAccessor(&r.Spec).SetField(spec)
}

func (r *TagKey) GetStatus() v1alpha1.MuxStatusInterface {
	return v1alpha1.NewMuxStatusAccessor(&r.Status).GetStatus()
}

func (r *TagKey) SetStatus(status v1alpha1.MuxStatusInterface) error {
	return v1alpha1.NewMuxStatusAccessor(&r.Status).SetStatus(status)
}

var _ v1alpha1.MuxReplicaInterface = &TagValueReplica{}

func (r *TagValueReplica) GetSpec() any {
	return v1alpha1.NewTypedFieldAccessor(&r.Spec).GetField()
}

func (r *TagValueReplica) SetSpec(spec any) error {
	return v1alpha1.NewTypedFieldAccessor(&r.Spec).SetField(spec)
}

func (r *TagValueReplica) GetStatus() any {
	return v1alpha1.NewTypedFieldAccessor(&r.Status).GetField()
}

func (r *TagValueReplica) SetStatus(status any) error {
	return v1alpha1.NewTypedFieldAccessor(&r.Status).SetField(status)
}

var _ v1alpha1.MuxStatusInterface = &TagValueStatus{}

func (s *TagValueStatus) GetZones() v1alpha1.ListMap[string, v1alpha1.ZoneStatusInterface] {
	return v1alpha1.NewZoneStatusListAccessor(&s.Zones).GetZones()
}

func (s *TagValueStatus) SetZones(zones v1alpha1.ListMap[string, v1alpha1.ZoneStatusInterface]) error {
	return v1alpha1.NewZoneStatusListAccessor(&s.Zones).SetZones(zones)
}

var _ v1alpha1.ZoneStatusInterface = &TagValueZoneStatus{}

func (s *TagValueZoneStatus) GetReplicaStatus() any {
	return v1alpha1.NewTypedFieldAccessor(&s.ReplicaStatus).GetField()
}

func (s *TagValueZoneStatus) SetReplicaStatus(replicaStatus any) error {
	return v1alpha1.NewTypedFieldAccessor(&s.ReplicaStatus).SetField(replicaStatus)
}

var _ v1alpha1.MuxResourceInterface = &TagValue{}

func (r *TagValue) GetSpec() any {
	return v1alpha1.NewTypedFieldAccessor(&r.Spec).GetField()
}

func (r *TagValue) SetSpec(spec any) error {
	return v1alpha1.NewTypedFieldAccessor(&r.Spec).SetField(spec)
}

func (r *TagValue) GetStatus() v1alpha1.MuxStatusInterface {
	return v1alpha1.NewMuxStatusAccessor(&r.Status).GetStatus()
}

func (r *TagValue) SetStatus(status v1alpha1.MuxStatusInterface) error {
	return v1alpha1.NewMuxStatusAccessor(&r.Status).SetStatus(status)
}
