// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"gke-internal.googlesource.com/private-cloud/pkg/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Project) DeepCopyInto(out *Project) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Project.
func (in *Project) DeepCopy() *Project {
	if in == nil {
		return nil
	}
	out := new(Project)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Project) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectList) DeepCopyInto(out *ProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Project, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectList.
func (in *ProjectList) DeepCopy() *ProjectList {
	if in == nil {
		return nil
	}
	out := new(ProjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectReplica) DeepCopyInto(out *ProjectReplica) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectReplica.
func (in *ProjectReplica) DeepCopy() *ProjectReplica {
	if in == nil {
		return nil
	}
	out := new(ProjectReplica)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectReplica) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectReplicaList) DeepCopyInto(out *ProjectReplicaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProjectReplica, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectReplicaList.
func (in *ProjectReplicaList) DeepCopy() *ProjectReplicaList {
	if in == nil {
		return nil
	}
	out := new(ProjectReplicaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectReplicaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectReplicaStatus) DeepCopyInto(out *ProjectReplicaStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ErrorStatus != nil {
		in, out := &in.ErrorStatus, &out.ErrorStatus
		*out = new(v1alpha1.ErrorStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectReplicaStatus.
func (in *ProjectReplicaStatus) DeepCopy() *ProjectReplicaStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectReplicaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectServiceAccount) DeepCopyInto(out *ProjectServiceAccount) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectServiceAccount.
func (in *ProjectServiceAccount) DeepCopy() *ProjectServiceAccount {
	if in == nil {
		return nil
	}
	out := new(ProjectServiceAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectServiceAccount) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectServiceAccountKey) DeepCopyInto(out *ProjectServiceAccountKey) {
	*out = *in
	in.ValidBefore.DeepCopyInto(&out.ValidBefore)
	in.ValidAfter.DeepCopyInto(&out.ValidAfter)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectServiceAccountKey.
func (in *ProjectServiceAccountKey) DeepCopy() *ProjectServiceAccountKey {
	if in == nil {
		return nil
	}
	out := new(ProjectServiceAccountKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectServiceAccountList) DeepCopyInto(out *ProjectServiceAccountList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProjectServiceAccount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectServiceAccountList.
func (in *ProjectServiceAccountList) DeepCopy() *ProjectServiceAccountList {
	if in == nil {
		return nil
	}
	out := new(ProjectServiceAccountList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectServiceAccountList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectServiceAccountReplica) DeepCopyInto(out *ProjectServiceAccountReplica) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectServiceAccountReplica.
func (in *ProjectServiceAccountReplica) DeepCopy() *ProjectServiceAccountReplica {
	if in == nil {
		return nil
	}
	out := new(ProjectServiceAccountReplica)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectServiceAccountReplica) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectServiceAccountReplicaList) DeepCopyInto(out *ProjectServiceAccountReplicaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProjectServiceAccountReplica, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectServiceAccountReplicaList.
func (in *ProjectServiceAccountReplicaList) DeepCopy() *ProjectServiceAccountReplicaList {
	if in == nil {
		return nil
	}
	out := new(ProjectServiceAccountReplicaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectServiceAccountReplicaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectServiceAccountReplicaStatus) DeepCopyInto(out *ProjectServiceAccountReplicaStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ErrorStatus != nil {
		in, out := &in.ErrorStatus, &out.ErrorStatus
		*out = new(v1alpha1.ErrorStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectServiceAccountReplicaStatus.
func (in *ProjectServiceAccountReplicaStatus) DeepCopy() *ProjectServiceAccountReplicaStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectServiceAccountReplicaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectServiceAccountSpec) DeepCopyInto(out *ProjectServiceAccountSpec) {
	*out = *in
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make([]ProjectServiceAccountKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectServiceAccountSpec.
func (in *ProjectServiceAccountSpec) DeepCopy() *ProjectServiceAccountSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectServiceAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectServiceAccountStatus) DeepCopyInto(out *ProjectServiceAccountStatus) {
	*out = *in
	in.MuxStatus.DeepCopyInto(&out.MuxStatus)
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]ProjectServiceAccountZoneStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectServiceAccountStatus.
func (in *ProjectServiceAccountStatus) DeepCopy() *ProjectServiceAccountStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectServiceAccountStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectServiceAccountZoneStatus) DeepCopyInto(out *ProjectServiceAccountZoneStatus) {
	*out = *in
	in.ZoneStatus.DeepCopyInto(&out.ZoneStatus)
	in.ReplicaStatus.DeepCopyInto(&out.ReplicaStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectServiceAccountZoneStatus.
func (in *ProjectServiceAccountZoneStatus) DeepCopy() *ProjectServiceAccountZoneStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectServiceAccountZoneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectSpec) DeepCopyInto(out *ProjectSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectSpec.
func (in *ProjectSpec) DeepCopy() *ProjectSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectStatus) DeepCopyInto(out *ProjectStatus) {
	*out = *in
	in.MuxStatus.DeepCopyInto(&out.MuxStatus)
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]ProjectZoneStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectStatus.
func (in *ProjectStatus) DeepCopy() *ProjectStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectZoneStatus) DeepCopyInto(out *ProjectZoneStatus) {
	*out = *in
	in.ZoneStatus.DeepCopyInto(&out.ZoneStatus)
	in.ReplicaStatus.DeepCopyInto(&out.ReplicaStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectZoneStatus.
func (in *ProjectZoneStatus) DeepCopy() *ProjectZoneStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectZoneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagKey) DeepCopyInto(out *TagKey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagKey.
func (in *TagKey) DeepCopy() *TagKey {
	if in == nil {
		return nil
	}
	out := new(TagKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TagKey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagKeyList) DeepCopyInto(out *TagKeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TagKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagKeyList.
func (in *TagKeyList) DeepCopy() *TagKeyList {
	if in == nil {
		return nil
	}
	out := new(TagKeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TagKeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagKeyReplica) DeepCopyInto(out *TagKeyReplica) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagKeyReplica.
func (in *TagKeyReplica) DeepCopy() *TagKeyReplica {
	if in == nil {
		return nil
	}
	out := new(TagKeyReplica)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TagKeyReplica) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagKeyReplicaList) DeepCopyInto(out *TagKeyReplicaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TagKeyReplica, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagKeyReplicaList.
func (in *TagKeyReplicaList) DeepCopy() *TagKeyReplicaList {
	if in == nil {
		return nil
	}
	out := new(TagKeyReplicaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TagKeyReplicaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagKeyReplicaStatus) DeepCopyInto(out *TagKeyReplicaStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ErrorStatus != nil {
		in, out := &in.ErrorStatus, &out.ErrorStatus
		*out = new(v1alpha1.ErrorStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagKeyReplicaStatus.
func (in *TagKeyReplicaStatus) DeepCopy() *TagKeyReplicaStatus {
	if in == nil {
		return nil
	}
	out := new(TagKeyReplicaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagKeySpec) DeepCopyInto(out *TagKeySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagKeySpec.
func (in *TagKeySpec) DeepCopy() *TagKeySpec {
	if in == nil {
		return nil
	}
	out := new(TagKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagKeyStatus) DeepCopyInto(out *TagKeyStatus) {
	*out = *in
	in.MuxStatus.DeepCopyInto(&out.MuxStatus)
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]TagKeyZoneStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagKeyStatus.
func (in *TagKeyStatus) DeepCopy() *TagKeyStatus {
	if in == nil {
		return nil
	}
	out := new(TagKeyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagKeyZoneStatus) DeepCopyInto(out *TagKeyZoneStatus) {
	*out = *in
	in.ZoneStatus.DeepCopyInto(&out.ZoneStatus)
	in.ReplicaStatus.DeepCopyInto(&out.ReplicaStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagKeyZoneStatus.
func (in *TagKeyZoneStatus) DeepCopy() *TagKeyZoneStatus {
	if in == nil {
		return nil
	}
	out := new(TagKeyZoneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagValue) DeepCopyInto(out *TagValue) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagValue.
func (in *TagValue) DeepCopy() *TagValue {
	if in == nil {
		return nil
	}
	out := new(TagValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TagValue) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagValueList) DeepCopyInto(out *TagValueList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TagValue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagValueList.
func (in *TagValueList) DeepCopy() *TagValueList {
	if in == nil {
		return nil
	}
	out := new(TagValueList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TagValueList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagValueReplica) DeepCopyInto(out *TagValueReplica) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagValueReplica.
func (in *TagValueReplica) DeepCopy() *TagValueReplica {
	if in == nil {
		return nil
	}
	out := new(TagValueReplica)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TagValueReplica) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagValueReplicaList) DeepCopyInto(out *TagValueReplicaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TagValueReplica, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagValueReplicaList.
func (in *TagValueReplicaList) DeepCopy() *TagValueReplicaList {
	if in == nil {
		return nil
	}
	out := new(TagValueReplicaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TagValueReplicaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagValueReplicaStatus) DeepCopyInto(out *TagValueReplicaStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ErrorStatus != nil {
		in, out := &in.ErrorStatus, &out.ErrorStatus
		*out = new(v1alpha1.ErrorStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagValueReplicaStatus.
func (in *TagValueReplicaStatus) DeepCopy() *TagValueReplicaStatus {
	if in == nil {
		return nil
	}
	out := new(TagValueReplicaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagValueSpec) DeepCopyInto(out *TagValueSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagValueSpec.
func (in *TagValueSpec) DeepCopy() *TagValueSpec {
	if in == nil {
		return nil
	}
	out := new(TagValueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagValueStatus) DeepCopyInto(out *TagValueStatus) {
	*out = *in
	in.MuxStatus.DeepCopyInto(&out.MuxStatus)
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]TagValueZoneStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagValueStatus.
func (in *TagValueStatus) DeepCopy() *TagValueStatus {
	if in == nil {
		return nil
	}
	out := new(TagValueStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagValueZoneStatus) DeepCopyInto(out *TagValueZoneStatus) {
	*out = *in
	in.ZoneStatus.DeepCopyInto(&out.ZoneStatus)
	in.ReplicaStatus.DeepCopyInto(&out.ReplicaStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagValueZoneStatus.
func (in *TagValueZoneStatus) DeepCopy() *TagValueZoneStatus {
	if in == nil {
		return nil
	}
	out := new(TagValueZoneStatus)
	in.DeepCopyInto(out)
	return out
}
