// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"github.com/googlecloudplatform/google-distributed-cloud-apis/pkg/apis/core/v1alpha1"
	backupv1 "github.com/googlecloudplatform/google-distributed-cloud-apis/pkg/apis/public/backup/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessManagementConfig) DeepCopyInto(out *AccessManagementConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessManagementConfig.
func (in *AccessManagementConfig) DeepCopy() *AccessManagementConfig {
	if in == nil {
		return nil
	}
	out := new(AccessManagementConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Compute) DeepCopyInto(out *Compute) {
	*out = *in
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Compute.
func (in *Compute) DeepCopy() *Compute {
	if in == nil {
		return nil
	}
	out := new(Compute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfidentialInstanceConfig) DeepCopyInto(out *ConfidentialInstanceConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfidentialInstanceConfig.
func (in *ConfidentialInstanceConfig) DeepCopy() *ConfidentialInstanceConfig {
	if in == nil {
		return nil
	}
	out := new(ConfidentialInstanceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskAttachment) DeepCopyInto(out *DiskAttachment) {
	*out = *in
	if in.Boot != nil {
		in, out := &in.Boot, &out.Boot
		*out = new(bool)
		**out = **in
	}
	if in.AutoDelete != nil {
		in, out := &in.AutoDelete, &out.AutoDelete
		*out = new(bool)
		**out = **in
	}
	out.VirtualMachineDiskRef = in.VirtualMachineDiskRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskAttachment.
func (in *DiskAttachment) DeepCopy() *DiskAttachment {
	if in == nil {
		return nil
	}
	out := new(DiskAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskReplicationStatus) DeepCopyInto(out *DiskReplicationStatus) {
	*out = *in
	if in.PrimaryDisk != nil {
		in, out := &in.PrimaryDisk, &out.PrimaryDisk
		*out = new(ReplicatedDiskInfo)
		**out = **in
	}
	if in.SecondaryDisk != nil {
		in, out := &in.SecondaryDisk, &out.SecondaryDisk
		*out = new(ReplicatedDiskInfo)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ErrorStatus != nil {
		in, out := &in.ErrorStatus, &out.ErrorStatus
		*out = new(v1alpha1.ErrorStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskReplicationStatus.
func (in *DiskReplicationStatus) DeepCopy() *DiskReplicationStatus {
	if in == nil {
		return nil
	}
	out := new(DiskReplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskSource) DeepCopyInto(out *DiskSource) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ImageDiskSource)
		**out = **in
	}
	if in.ImageFamily != nil {
		in, out := &in.ImageFamily, &out.ImageFamily
		*out = new(ImageFamilySource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskSource.
func (in *DiskSource) DeepCopy() *DiskSource {
	if in == nil {
		return nil
	}
	out := new(DiskSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailureHistory) DeepCopyInto(out *FailureHistory) {
	*out = *in
	if in.FailureInfos != nil {
		in, out := &in.FailureInfos, &out.FailureInfos
		*out = make([]FailureInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailureHistory.
func (in *FailureHistory) DeepCopy() *FailureHistory {
	if in == nil {
		return nil
	}
	out := new(FailureHistory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailureInfo) DeepCopyInto(out *FailureInfo) {
	*out = *in
	in.ObservedTime.DeepCopyInto(&out.ObservedTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailureInfo.
func (in *FailureInfo) DeepCopy() *FailureInfo {
	if in == nil {
		return nil
	}
	out := new(FailureInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterSpec) DeepCopyInto(out *FilterSpec) {
	*out = *in
	if in.TargetedVirtualMachines != nil {
		in, out := &in.TargetedVirtualMachines, &out.TargetedVirtualMachines
		*out = make([]VirtualMachineResourceConfig, len(*in))
		copy(*out, *in)
	}
	if in.TargetedVirtualMachineDisks != nil {
		in, out := &in.TargetedVirtualMachineDisks, &out.TargetedVirtualMachineDisks
		*out = make([]VirtualMachineResourceConfig, len(*in))
		copy(*out, *in)
	}
	if in.VirtualMachineDiskOptions != nil {
		in, out := &in.VirtualMachineDiskOptions, &out.VirtualMachineDiskOptions
		*out = new(VirtualMachineDiskFilterOptions)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterSpec.
func (in *FilterSpec) DeepCopy() *FilterSpec {
	if in == nil {
		return nil
	}
	out := new(FilterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Firmware) DeepCopyInto(out *Firmware) {
	*out = *in
	if in.EnableSecureBoot != nil {
		in, out := &in.EnableSecureBoot, &out.EnableSecureBoot
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Firmware.
func (in *Firmware) DeepCopy() *Firmware {
	if in == nil {
		return nil
	}
	out := new(Firmware)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCSReference) DeepCopyInto(out *GCSReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCSReference.
func (in *GCSReference) DeepCopy() *GCSReference {
	if in == nil {
		return nil
	}
	out := new(GCSReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GracefulShutdown) DeepCopyInto(out *GracefulShutdown) {
	*out = *in
	if in.ConnectionDrainTimeoutSeconds != nil {
		in, out := &in.ConnectionDrainTimeoutSeconds, &out.ConnectionDrainTimeoutSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GracefulShutdown.
func (in *GracefulShutdown) DeepCopy() *GracefulShutdown {
	if in == nil {
		return nil
	}
	out := new(GracefulShutdown)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuestEnvironment) DeepCopyInto(out *GuestEnvironment) {
	*out = *in
	if in.AccessManagement != nil {
		in, out := &in.AccessManagement, &out.AccessManagement
		*out = new(AccessManagementConfig)
		**out = **in
	}
	if in.GuestHealthCheck != nil {
		in, out := &in.GuestHealthCheck, &out.GuestHealthCheck
		*out = new(GuestHealthCheck)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuestEnvironment.
func (in *GuestEnvironment) DeepCopy() *GuestEnvironment {
	if in == nil {
		return nil
	}
	out := new(GuestEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuestHealthCheck) DeepCopyInto(out *GuestHealthCheck) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuestHealthCheck.
func (in *GuestHealthCheck) DeepCopy() *GuestHealthCheck {
	if in == nil {
		return nil
	}
	out := new(GuestHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPAddress) DeepCopyInto(out *IPAddress) {
	*out = *in
	if in.Managed != nil {
		in, out := &in.Managed, &out.Managed
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPAddress.
func (in *IPAddress) DeepCopy() *IPAddress {
	if in == nil {
		return nil
	}
	out := new(IPAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageDestinationReference) DeepCopyInto(out *ImageDestinationReference) {
	*out = *in
	if in.GCS != nil {
		in, out := &in.GCS, &out.GCS
		*out = new(ImageGCSDestinationReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageDestinationReference.
func (in *ImageDestinationReference) DeepCopy() *ImageDestinationReference {
	if in == nil {
		return nil
	}
	out := new(ImageDestinationReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageDiskSource) DeepCopyInto(out *ImageDiskSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageDiskSource.
func (in *ImageDiskSource) DeepCopy() *ImageDiskSource {
	if in == nil {
		return nil
	}
	out := new(ImageDiskSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageFamilySource) DeepCopyInto(out *ImageFamilySource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageFamilySource.
func (in *ImageFamilySource) DeepCopy() *ImageFamilySource {
	if in == nil {
		return nil
	}
	out := new(ImageFamilySource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageGCSDestinationReference) DeepCopyInto(out *ImageGCSDestinationReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageGCSDestinationReference.
func (in *ImageGCSDestinationReference) DeepCopy() *ImageGCSDestinationReference {
	if in == nil {
		return nil
	}
	out := new(ImageGCSDestinationReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageGCSSourceReference) DeepCopyInto(out *ImageGCSSourceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageGCSSourceReference.
func (in *ImageGCSSourceReference) DeepCopy() *ImageGCSSourceReference {
	if in == nil {
		return nil
	}
	out := new(ImageGCSSourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageMetadataInput) DeepCopyInto(out *ImageMetadataInput) {
	*out = *in
	if in.MinimumDiskSize != nil {
		in, out := &in.MinimumDiskSize, &out.MinimumDiskSize
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageMetadataInput.
func (in *ImageMetadataInput) DeepCopy() *ImageMetadataInput {
	if in == nil {
		return nil
	}
	out := new(ImageMetadataInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageObjectStorageSourceReference) DeepCopyInto(out *ImageObjectStorageSourceReference) {
	*out = *in
	out.BucketRef = in.BucketRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageObjectStorageSourceReference.
func (in *ImageObjectStorageSourceReference) DeepCopy() *ImageObjectStorageSourceReference {
	if in == nil {
		return nil
	}
	out := new(ImageObjectStorageSourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePrepareOptions) DeepCopyInto(out *ImagePrepareOptions) {
	*out = *in
	if in.InstallGuestEnvironment != nil {
		in, out := &in.InstallGuestEnvironment, &out.InstallGuestEnvironment
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePrepareOptions.
func (in *ImagePrepareOptions) DeepCopy() *ImagePrepareOptions {
	if in == nil {
		return nil
	}
	out := new(ImagePrepareOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSourceReference) DeepCopyInto(out *ImageSourceReference) {
	*out = *in
	if in.DiskRef != nil {
		in, out := &in.DiskRef, &out.DiskRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.ObjectStorage != nil {
		in, out := &in.ObjectStorage, &out.ObjectStorage
		*out = new(ImageObjectStorageSourceReference)
		**out = **in
	}
	if in.GCS != nil {
		in, out := &in.GCS, &out.GCS
		*out = new(ImageGCSSourceReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSourceReference.
func (in *ImageSourceReference) DeepCopy() *ImageSourceReference {
	if in == nil {
		return nil
	}
	out := new(ImageSourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInterfaceSpec) DeepCopyInto(out *NetworkInterfaceSpec) {
	*out = *in
	if in.IPAddresses != nil {
		in, out := &in.IPAddresses, &out.IPAddresses
		*out = make([]IPAddress, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInterfaceSpec.
func (in *NetworkInterfaceSpec) DeepCopy() *NetworkInterfaceSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkInterfaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInterfaceStatus) DeepCopyInto(out *NetworkInterfaceStatus) {
	*out = *in
	if in.IpAddresses != nil {
		in, out := &in.IpAddresses, &out.IpAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Subnet = in.Subnet
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInterfaceStatus.
func (in *NetworkInterfaceStatus) DeepCopy() *NetworkInterfaceStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkInterfaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSpec) DeepCopyInto(out *NetworkSpec) {
	*out = *in
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]NetworkInterfaceSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSpec.
func (in *NetworkSpec) DeepCopy() *NetworkSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkStatus) DeepCopyInto(out *NetworkStatus) {
	*out = *in
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]NetworkInterfaceStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkStatus.
func (in *NetworkStatus) DeepCopy() *NetworkStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatingSystemSpec) DeepCopyInto(out *OperatingSystemSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatingSystemSpec.
func (in *OperatingSystemSpec) DeepCopy() *OperatingSystemSpec {
	if in == nil {
		return nil
	}
	out := new(OperatingSystemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedDiskInfo) DeepCopyInto(out *ReplicatedDiskInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedDiskInfo.
func (in *ReplicatedDiskInfo) DeepCopy() *ReplicatedDiskInfo {
	if in == nil {
		return nil
	}
	out := new(ReplicatedDiskInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHSpec) DeepCopyInto(out *SSHSpec) {
	*out = *in
	out.TTL = in.TTL
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHSpec.
func (in *SSHSpec) DeepCopy() *SSHSpec {
	if in == nil {
		return nil
	}
	out := new(SSHSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicePort) DeepCopyInto(out *ServicePort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicePort.
func (in *ServicePort) DeepCopy() *ServicePort {
	if in == nil {
		return nil
	}
	out := new(ServicePort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShieldConfig) DeepCopyInto(out *ShieldConfig) {
	*out = *in
	if in.EnableSecureBoot != nil {
		in, out := &in.EnableSecureBoot, &out.EnableSecureBoot
		*out = new(bool)
		**out = **in
	}
	if in.EnableVtpm != nil {
		in, out := &in.EnableVtpm, &out.EnableVtpm
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShieldConfig.
func (in *ShieldConfig) DeepCopy() *ShieldConfig {
	if in == nil {
		return nil
	}
	out := new(ShieldConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StartupScript) DeepCopyInto(out *StartupScript) {
	*out = *in
	if in.ScriptSecretRef != nil {
		in, out := &in.ScriptSecretRef, &out.ScriptSecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartupScript.
func (in *StartupScript) DeepCopy() *StartupScript {
	if in == nil {
		return nil
	}
	out := new(StartupScript)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetReference) DeepCopyInto(out *SubnetReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetReference.
func (in *SubnetReference) DeepCopy() *SubnetReference {
	if in == nil {
		return nil
	}
	out := new(SubnetReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMMError) DeepCopyInto(out *VMMError) {
	*out = *in
	out.BaseError = in.BaseError
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMMError.
func (in *VMMError) DeepCopy() *VMMError {
	if in == nil {
		return nil
	}
	out := new(VMMError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachine) DeepCopyInto(out *VirtualMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachine.
func (in *VirtualMachine) DeepCopy() *VirtualMachine {
	if in == nil {
		return nil
	}
	out := new(VirtualMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineAccessRequest) DeepCopyInto(out *VirtualMachineAccessRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineAccessRequest.
func (in *VirtualMachineAccessRequest) DeepCopy() *VirtualMachineAccessRequest {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineAccessRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineAccessRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineAccessRequestList) DeepCopyInto(out *VirtualMachineAccessRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachineAccessRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineAccessRequestList.
func (in *VirtualMachineAccessRequestList) DeepCopy() *VirtualMachineAccessRequestList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineAccessRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineAccessRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineAccessRequestSpec) DeepCopyInto(out *VirtualMachineAccessRequestSpec) {
	*out = *in
	out.SSH = in.SSH
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineAccessRequestSpec.
func (in *VirtualMachineAccessRequestSpec) DeepCopy() *VirtualMachineAccessRequestSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineAccessRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineAccessRequestStatus) DeepCopyInto(out *VirtualMachineAccessRequestStatus) {
	*out = *in
	in.ProcessedAt.DeepCopyInto(&out.ProcessedAt)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]VMMError, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineAccessRequestStatus.
func (in *VirtualMachineAccessRequestStatus) DeepCopy() *VirtualMachineAccessRequestStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineAccessRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineAttachedDiskStatus) DeepCopyInto(out *VirtualMachineAttachedDiskStatus) {
	*out = *in
	if in.Hotpluggable != nil {
		in, out := &in.Hotpluggable, &out.Hotpluggable
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineAttachedDiskStatus.
func (in *VirtualMachineAttachedDiskStatus) DeepCopy() *VirtualMachineAttachedDiskStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineAttachedDiskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineAttachedDisksInfo) DeepCopyInto(out *VirtualMachineAttachedDisksInfo) {
	*out = *in
	if in.Attachments != nil {
		in, out := &in.Attachments, &out.Attachments
		*out = make([]VirtualMachineAttachedDiskStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineAttachedDisksInfo.
func (in *VirtualMachineAttachedDisksInfo) DeepCopy() *VirtualMachineAttachedDisksInfo {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineAttachedDisksInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineAttachment) DeepCopyInto(out *VirtualMachineAttachment) {
	*out = *in
	out.NameRef = in.NameRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineAttachment.
func (in *VirtualMachineAttachment) DeepCopy() *VirtualMachineAttachment {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineBackup) DeepCopyInto(out *VirtualMachineBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineBackup.
func (in *VirtualMachineBackup) DeepCopy() *VirtualMachineBackup {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineBackupConfig) DeepCopyInto(out *VirtualMachineBackupConfig) {
	*out = *in
	in.BackupScope.DeepCopyInto(&out.BackupScope)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineBackupConfig.
func (in *VirtualMachineBackupConfig) DeepCopy() *VirtualMachineBackupConfig {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineBackupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineBackupList) DeepCopyInto(out *VirtualMachineBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachineBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineBackupList.
func (in *VirtualMachineBackupList) DeepCopy() *VirtualMachineBackupList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineBackupPlan) DeepCopyInto(out *VirtualMachineBackupPlan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineBackupPlan.
func (in *VirtualMachineBackupPlan) DeepCopy() *VirtualMachineBackupPlan {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineBackupPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineBackupPlan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineBackupPlanList) DeepCopyInto(out *VirtualMachineBackupPlanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachineBackupPlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineBackupPlanList.
func (in *VirtualMachineBackupPlanList) DeepCopy() *VirtualMachineBackupPlanList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineBackupPlanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineBackupPlanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineBackupPlanSpec) DeepCopyInto(out *VirtualMachineBackupPlanSpec) {
	*out = *in
	in.BackupConfig.DeepCopyInto(&out.BackupConfig)
	if in.BackupSchedule != nil {
		in, out := &in.BackupSchedule, &out.BackupSchedule
		*out = new(backupv1.Schedule)
		(*in).DeepCopyInto(*out)
	}
	if in.RetentionPolicy != nil {
		in, out := &in.RetentionPolicy, &out.RetentionPolicy
		*out = new(backupv1.RetentionPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineBackupPlanSpec.
func (in *VirtualMachineBackupPlanSpec) DeepCopy() *VirtualMachineBackupPlanSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineBackupPlanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineBackupPlanStatus) DeepCopyInto(out *VirtualMachineBackupPlanStatus) {
	*out = *in
	if in.BackupPlan != nil {
		in, out := &in.BackupPlan, &out.BackupPlan
		*out = new(string)
		**out = **in
	}
	if in.BackupPlanStatus != nil {
		in, out := &in.BackupPlanStatus, &out.BackupPlanStatus
		*out = new(backupv1.BackupPlanStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigBackupPlan != nil {
		in, out := &in.ConfigBackupPlan, &out.ConfigBackupPlan
		*out = new(string)
		**out = **in
	}
	if in.VolumeBackupPlan != nil {
		in, out := &in.VolumeBackupPlan, &out.VolumeBackupPlan
		*out = new(string)
		**out = **in
	}
	in.LastBackupTime.DeepCopyInto(&out.LastBackupTime)
	in.NextBackupTime.DeepCopyInto(&out.NextBackupTime)
	in.LastReconcileTime.DeepCopyInto(&out.LastReconcileTime)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineBackupPlanStatus.
func (in *VirtualMachineBackupPlanStatus) DeepCopy() *VirtualMachineBackupPlanStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineBackupPlanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineBackupPlanTemplate) DeepCopyInto(out *VirtualMachineBackupPlanTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineBackupPlanTemplate.
func (in *VirtualMachineBackupPlanTemplate) DeepCopy() *VirtualMachineBackupPlanTemplate {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineBackupPlanTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineBackupPlanTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineBackupPlanTemplateList) DeepCopyInto(out *VirtualMachineBackupPlanTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachineBackupPlanTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineBackupPlanTemplateList.
func (in *VirtualMachineBackupPlanTemplateList) DeepCopy() *VirtualMachineBackupPlanTemplateList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineBackupPlanTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineBackupPlanTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineBackupPlanTemplateSpec) DeepCopyInto(out *VirtualMachineBackupPlanTemplateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineBackupPlanTemplateSpec.
func (in *VirtualMachineBackupPlanTemplateSpec) DeepCopy() *VirtualMachineBackupPlanTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineBackupPlanTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineBackupPlanTemplateStatus) DeepCopyInto(out *VirtualMachineBackupPlanTemplateStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineBackupPlanTemplateStatus.
func (in *VirtualMachineBackupPlanTemplateStatus) DeepCopy() *VirtualMachineBackupPlanTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineBackupPlanTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineBackupRequest) DeepCopyInto(out *VirtualMachineBackupRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineBackupRequest.
func (in *VirtualMachineBackupRequest) DeepCopy() *VirtualMachineBackupRequest {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineBackupRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineBackupRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineBackupRequestList) DeepCopyInto(out *VirtualMachineBackupRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachineBackupRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineBackupRequestList.
func (in *VirtualMachineBackupRequestList) DeepCopy() *VirtualMachineBackupRequestList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineBackupRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineBackupRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineBackupRequestSpec) DeepCopyInto(out *VirtualMachineBackupRequestSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineBackupRequestSpec.
func (in *VirtualMachineBackupRequestSpec) DeepCopy() *VirtualMachineBackupRequestSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineBackupRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineBackupRequestStatus) DeepCopyInto(out *VirtualMachineBackupRequestStatus) {
	*out = *in
	in.TimeToExpire.DeepCopyInto(&out.TimeToExpire)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineBackupRequestStatus.
func (in *VirtualMachineBackupRequestStatus) DeepCopy() *VirtualMachineBackupRequestStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineBackupRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineBackupScope) DeepCopyInto(out *VirtualMachineBackupScope) {
	*out = *in
	if in.SelectedVirtualMachines != nil {
		in, out := &in.SelectedVirtualMachines, &out.SelectedVirtualMachines
		*out = make([]VirtualMachineResourceConfig, len(*in))
		copy(*out, *in)
	}
	if in.SelectedVirtualMachineDisks != nil {
		in, out := &in.SelectedVirtualMachineDisks, &out.SelectedVirtualMachineDisks
		*out = make([]VirtualMachineResourceConfig, len(*in))
		copy(*out, *in)
	}
	if in.VMResourceLabelSelector != nil {
		in, out := &in.VMResourceLabelSelector, &out.VMResourceLabelSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineBackupScope.
func (in *VirtualMachineBackupScope) DeepCopy() *VirtualMachineBackupScope {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineBackupScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineBackupSpec) DeepCopyInto(out *VirtualMachineBackupSpec) {
	*out = *in
	in.BackupConfig.DeepCopyInto(&out.BackupConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineBackupSpec.
func (in *VirtualMachineBackupSpec) DeepCopy() *VirtualMachineBackupSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineBackupStatus) DeepCopyInto(out *VirtualMachineBackupStatus) {
	*out = *in
	in.BackupStatus.DeepCopyInto(&out.BackupStatus)
	in.ConfigBackupStatus.DeepCopyInto(&out.ConfigBackupStatus)
	in.VolumeBackupStatus.DeepCopyInto(&out.VolumeBackupStatus)
	if in.BackedUpVirtualMachines != nil {
		in, out := &in.BackedUpVirtualMachines, &out.BackedUpVirtualMachines
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BackedUpVirtualMachineDisks != nil {
		in, out := &in.BackedUpVirtualMachineDisks, &out.BackedUpVirtualMachineDisks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SuccessfulVirtualMachines != nil {
		in, out := &in.SuccessfulVirtualMachines, &out.SuccessfulVirtualMachines
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FailedVirtualMachines != nil {
		in, out := &in.FailedVirtualMachines, &out.FailedVirtualMachines
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SuccessfulVirtualMachineDisks != nil {
		in, out := &in.SuccessfulVirtualMachineDisks, &out.SuccessfulVirtualMachineDisks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FailedVirtualMachineDisks != nil {
		in, out := &in.FailedVirtualMachineDisks, &out.FailedVirtualMachineDisks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineBackupStatus.
func (in *VirtualMachineBackupStatus) DeepCopy() *VirtualMachineBackupStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineDeleteBackupRequest) DeepCopyInto(out *VirtualMachineDeleteBackupRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineDeleteBackupRequest.
func (in *VirtualMachineDeleteBackupRequest) DeepCopy() *VirtualMachineDeleteBackupRequest {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineDeleteBackupRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineDeleteBackupRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineDeleteBackupRequestList) DeepCopyInto(out *VirtualMachineDeleteBackupRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachineDeleteBackupRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineDeleteBackupRequestList.
func (in *VirtualMachineDeleteBackupRequestList) DeepCopy() *VirtualMachineDeleteBackupRequestList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineDeleteBackupRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineDeleteBackupRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineDeleteBackupRequestSpec) DeepCopyInto(out *VirtualMachineDeleteBackupRequestSpec) {
	*out = *in
	out.VirtualMachineBackupRef = in.VirtualMachineBackupRef
	if in.TargetedVMBackupJobNames != nil {
		in, out := &in.TargetedVMBackupJobNames, &out.TargetedVMBackupJobNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineDeleteBackupRequestSpec.
func (in *VirtualMachineDeleteBackupRequestSpec) DeepCopy() *VirtualMachineDeleteBackupRequestSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineDeleteBackupRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineDeleteBackupRequestStatus) DeepCopyInto(out *VirtualMachineDeleteBackupRequestStatus) {
	*out = *in
	in.TimeToExpire.DeepCopyInto(&out.TimeToExpire)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineDeleteBackupRequestStatus.
func (in *VirtualMachineDeleteBackupRequestStatus) DeepCopy() *VirtualMachineDeleteBackupRequestStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineDeleteBackupRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineDisk) DeepCopyInto(out *VirtualMachineDisk) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineDisk.
func (in *VirtualMachineDisk) DeepCopy() *VirtualMachineDisk {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineDisk) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineDiskFilterOptions) DeepCopyInto(out *VirtualMachineDiskFilterOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineDiskFilterOptions.
func (in *VirtualMachineDiskFilterOptions) DeepCopy() *VirtualMachineDiskFilterOptions {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineDiskFilterOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineDiskList) DeepCopyInto(out *VirtualMachineDiskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachineDisk, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineDiskList.
func (in *VirtualMachineDiskList) DeepCopy() *VirtualMachineDiskList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineDiskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineDiskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineDiskSpec) DeepCopyInto(out *VirtualMachineDiskSpec) {
	*out = *in
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(DiskSource)
		(*in).DeepCopyInto(*out)
	}
	out.Size = in.Size.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineDiskSpec.
func (in *VirtualMachineDiskSpec) DeepCopy() *VirtualMachineDiskSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineDiskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineDiskStatus) DeepCopyInto(out *VirtualMachineDiskStatus) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VirtualMachineAttachments != nil {
		in, out := &in.VirtualMachineAttachments, &out.VirtualMachineAttachments
		*out = make([]VirtualMachineAttachment, len(*in))
		copy(*out, *in)
	}
	if in.ReplicationStatus != nil {
		in, out := &in.ReplicationStatus, &out.ReplicationStatus
		*out = new(DiskReplicationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ProvisionTime != nil {
		in, out := &in.ProvisionTime, &out.ProvisionTime
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]VMMError, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineDiskStatus.
func (in *VirtualMachineDiskStatus) DeepCopy() *VirtualMachineDiskStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineDiskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineExternalAccess) DeepCopyInto(out *VirtualMachineExternalAccess) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineExternalAccess.
func (in *VirtualMachineExternalAccess) DeepCopy() *VirtualMachineExternalAccess {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineExternalAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineExternalAccess) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineExternalAccessList) DeepCopyInto(out *VirtualMachineExternalAccessList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachineExternalAccess, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineExternalAccessList.
func (in *VirtualMachineExternalAccessList) DeepCopy() *VirtualMachineExternalAccessList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineExternalAccessList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineExternalAccessList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineExternalAccessSpec) DeepCopyInto(out *VirtualMachineExternalAccessSpec) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]ServicePort, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineExternalAccessSpec.
func (in *VirtualMachineExternalAccessSpec) DeepCopy() *VirtualMachineExternalAccessSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineExternalAccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineExternalAccessStatus) DeepCopyInto(out *VirtualMachineExternalAccessStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]VMMError, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineExternalAccessStatus.
func (in *VirtualMachineExternalAccessStatus) DeepCopy() *VirtualMachineExternalAccessStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineExternalAccessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineImage) DeepCopyInto(out *VirtualMachineImage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineImage.
func (in *VirtualMachineImage) DeepCopy() *VirtualMachineImage {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineImage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineImageImport) DeepCopyInto(out *VirtualMachineImageImport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineImageImport.
func (in *VirtualMachineImageImport) DeepCopy() *VirtualMachineImageImport {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineImageImport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineImageImport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineImageImportList) DeepCopyInto(out *VirtualMachineImageImportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachineImageImport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineImageImportList.
func (in *VirtualMachineImageImportList) DeepCopy() *VirtualMachineImageImportList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineImageImportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineImageImportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineImageImportSpec) DeepCopyInto(out *VirtualMachineImageImportSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	in.Destination.DeepCopyInto(&out.Destination)
	in.ImageMetadata.DeepCopyInto(&out.ImageMetadata)
	if in.PrepareImage != nil {
		in, out := &in.PrepareImage, &out.PrepareImage
		*out = new(bool)
		**out = **in
	}
	in.PrepareOptions.DeepCopyInto(&out.PrepareOptions)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineImageImportSpec.
func (in *VirtualMachineImageImportSpec) DeepCopy() *VirtualMachineImageImportSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineImageImportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineImageImportStatus) DeepCopyInto(out *VirtualMachineImageImportStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TransitionTime != nil {
		in, out := &in.TransitionTime, &out.TransitionTime
		*out = make([]VirtualMachineImageImportTransitionTime, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]VMMError, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineImageImportStatus.
func (in *VirtualMachineImageImportStatus) DeepCopy() *VirtualMachineImageImportStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineImageImportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineImageImportTransitionTime) DeepCopyInto(out *VirtualMachineImageImportTransitionTime) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineImageImportTransitionTime.
func (in *VirtualMachineImageImportTransitionTime) DeepCopy() *VirtualMachineImageImportTransitionTime {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineImageImportTransitionTime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineImageList) DeepCopyInto(out *VirtualMachineImageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachineImage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineImageList.
func (in *VirtualMachineImageList) DeepCopy() *VirtualMachineImageList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineImageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineImageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineImageSpec) DeepCopyInto(out *VirtualMachineImageSpec) {
	*out = *in
	out.OperatingSystem = in.OperatingSystem
	if in.MinimumDiskSize != nil {
		in, out := &in.MinimumDiskSize, &out.MinimumDiskSize
		x := (*in).DeepCopy()
		*out = &x
	}
	out.GCS = in.GCS
	if in.BuildTime != nil {
		in, out := &in.BuildTime, &out.BuildTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineImageSpec.
func (in *VirtualMachineImageSpec) DeepCopy() *VirtualMachineImageSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineImageStatus) DeepCopyInto(out *VirtualMachineImageStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]VMMError, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineImageStatus.
func (in *VirtualMachineImageStatus) DeepCopy() *VirtualMachineImageStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineImageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineList) DeepCopyInto(out *VirtualMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineList.
func (in *VirtualMachineList) DeepCopy() *VirtualMachineList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachinePasswordResetRequest) DeepCopyInto(out *VirtualMachinePasswordResetRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachinePasswordResetRequest.
func (in *VirtualMachinePasswordResetRequest) DeepCopy() *VirtualMachinePasswordResetRequest {
	if in == nil {
		return nil
	}
	out := new(VirtualMachinePasswordResetRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachinePasswordResetRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachinePasswordResetRequestList) DeepCopyInto(out *VirtualMachinePasswordResetRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachinePasswordResetRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachinePasswordResetRequestList.
func (in *VirtualMachinePasswordResetRequestList) DeepCopy() *VirtualMachinePasswordResetRequestList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachinePasswordResetRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachinePasswordResetRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachinePasswordResetRequestSpec) DeepCopyInto(out *VirtualMachinePasswordResetRequestSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachinePasswordResetRequestSpec.
func (in *VirtualMachinePasswordResetRequestSpec) DeepCopy() *VirtualMachinePasswordResetRequestSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachinePasswordResetRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachinePasswordResetRequestStatus) DeepCopyInto(out *VirtualMachinePasswordResetRequestStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.ProcessedAt.DeepCopyInto(&out.ProcessedAt)
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]VMMError, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachinePasswordResetRequestStatus.
func (in *VirtualMachinePasswordResetRequestStatus) DeepCopy() *VirtualMachinePasswordResetRequestStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachinePasswordResetRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineProvisionTime) DeepCopyInto(out *VirtualMachineProvisionTime) {
	*out = *in
	if in.InitProvisionTime != nil {
		in, out := &in.InitProvisionTime, &out.InitProvisionTime
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.LastProvisionTime != nil {
		in, out := &in.LastProvisionTime, &out.LastProvisionTime
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineProvisionTime.
func (in *VirtualMachineProvisionTime) DeepCopy() *VirtualMachineProvisionTime {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineProvisionTime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineResourceConfig) DeepCopyInto(out *VirtualMachineResourceConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineResourceConfig.
func (in *VirtualMachineResourceConfig) DeepCopy() *VirtualMachineResourceConfig {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineResourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineRestore) DeepCopyInto(out *VirtualMachineRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineRestore.
func (in *VirtualMachineRestore) DeepCopy() *VirtualMachineRestore {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineRestoreList) DeepCopyInto(out *VirtualMachineRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachineRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineRestoreList.
func (in *VirtualMachineRestoreList) DeepCopy() *VirtualMachineRestoreList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineRestoreRequest) DeepCopyInto(out *VirtualMachineRestoreRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineRestoreRequest.
func (in *VirtualMachineRestoreRequest) DeepCopy() *VirtualMachineRestoreRequest {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineRestoreRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineRestoreRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineRestoreRequestList) DeepCopyInto(out *VirtualMachineRestoreRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachineRestoreRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineRestoreRequestList.
func (in *VirtualMachineRestoreRequestList) DeepCopy() *VirtualMachineRestoreRequestList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineRestoreRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineRestoreRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineRestoreRequestSpec) DeepCopyInto(out *VirtualMachineRestoreRequestSpec) {
	*out = *in
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = new(FilterSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineRestoreRequestSpec.
func (in *VirtualMachineRestoreRequestSpec) DeepCopy() *VirtualMachineRestoreRequestSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineRestoreRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineRestoreRequestStatus) DeepCopyInto(out *VirtualMachineRestoreRequestStatus) {
	*out = *in
	in.TimeToExpire.DeepCopyInto(&out.TimeToExpire)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineRestoreRequestStatus.
func (in *VirtualMachineRestoreRequestStatus) DeepCopy() *VirtualMachineRestoreRequestStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineRestoreRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineRestoreSpec) DeepCopyInto(out *VirtualMachineRestoreSpec) {
	*out = *in
	if in.TargetVirtualMachines != nil {
		in, out := &in.TargetVirtualMachines, &out.TargetVirtualMachines
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TargetVirtualMachineDisks != nil {
		in, out := &in.TargetVirtualMachineDisks, &out.TargetVirtualMachineDisks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineRestoreSpec.
func (in *VirtualMachineRestoreSpec) DeepCopy() *VirtualMachineRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineRestoreStatus) DeepCopyInto(out *VirtualMachineRestoreStatus) {
	*out = *in
	in.RestoreStatus.DeepCopyInto(&out.RestoreStatus)
	in.ConfigRestoreStatus.DeepCopyInto(&out.ConfigRestoreStatus)
	in.VolumeRestoreStatus.DeepCopyInto(&out.VolumeRestoreStatus)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineRestoreStatus.
func (in *VirtualMachineRestoreStatus) DeepCopy() *VirtualMachineRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineSpec) DeepCopyInto(out *VirtualMachineSpec) {
	*out = *in
	if in.RunningState != nil {
		in, out := &in.RunningState, &out.RunningState
		*out = new(VirtualMachineRunningState)
		**out = **in
	}
	if in.Disks != nil {
		in, out := &in.Disks, &out.Disks
		*out = make([]DiskAttachment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Compute.DeepCopyInto(&out.Compute)
	if in.ConfidentialInstanceConfig != nil {
		in, out := &in.ConfidentialInstanceConfig, &out.ConfidentialInstanceConfig
		*out = new(ConfidentialInstanceConfig)
		**out = **in
	}
	if in.StartupScripts != nil {
		in, out := &in.StartupScripts, &out.StartupScripts
		*out = make([]StartupScript, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GuestEnvironment != nil {
		in, out := &in.GuestEnvironment, &out.GuestEnvironment
		*out = new(GuestEnvironment)
		(*in).DeepCopyInto(*out)
	}
	if in.Firmware != nil {
		in, out := &in.Firmware, &out.Firmware
		*out = new(Firmware)
		(*in).DeepCopyInto(*out)
	}
	if in.ShieldConfig != nil {
		in, out := &in.ShieldConfig, &out.ShieldConfig
		*out = new(ShieldConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(NetworkSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TemplateRef != nil {
		in, out := &in.TemplateRef, &out.TemplateRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.GracefulShutdown != nil {
		in, out := &in.GracefulShutdown, &out.GracefulShutdown
		*out = new(GracefulShutdown)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineSpec.
func (in *VirtualMachineSpec) DeepCopy() *VirtualMachineSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineStatus) DeepCopyInto(out *VirtualMachineStatus) {
	*out = *in
	in.Network.DeepCopyInto(&out.Network)
	if in.Disks != nil {
		in, out := &in.Disks, &out.Disks
		*out = new(VirtualMachineAttachedDisksInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StateTransitionTime != nil {
		in, out := &in.StateTransitionTime, &out.StateTransitionTime
		*out = make(map[VirtualMachineState]metav1.Time, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.TransitionTime != nil {
		in, out := &in.TransitionTime, &out.TransitionTime
		*out = make([]VirtualMachineTransitionTime, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProvisionTime != nil {
		in, out := &in.ProvisionTime, &out.ProvisionTime
		*out = new(VirtualMachineProvisionTime)
		(*in).DeepCopyInto(*out)
	}
	if in.FailureHistory != nil {
		in, out := &in.FailureHistory, &out.FailureHistory
		*out = new(FailureHistory)
		(*in).DeepCopyInto(*out)
	}
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]VMMError, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineStatus.
func (in *VirtualMachineStatus) DeepCopy() *VirtualMachineStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineTransitionTime) DeepCopyInto(out *VirtualMachineTransitionTime) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineTransitionTime.
func (in *VirtualMachineTransitionTime) DeepCopy() *VirtualMachineTransitionTime {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineTransitionTime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineType) DeepCopyInto(out *VirtualMachineType) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineType.
func (in *VirtualMachineType) DeepCopy() *VirtualMachineType {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineType) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineTypeList) DeepCopyInto(out *VirtualMachineTypeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachineType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineTypeList.
func (in *VirtualMachineTypeList) DeepCopy() *VirtualMachineTypeList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineTypeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineTypeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineTypeSpec) DeepCopyInto(out *VirtualMachineTypeSpec) {
	*out = *in
	out.Memory = in.Memory.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineTypeSpec.
func (in *VirtualMachineTypeSpec) DeepCopy() *VirtualMachineTypeSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineTypeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineTypeStatus) DeepCopyInto(out *VirtualMachineTypeStatus) {
	*out = *in
	if in.Supported != nil {
		in, out := &in.Supported, &out.Supported
		*out = new(bool)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineTypeStatus.
func (in *VirtualMachineTypeStatus) DeepCopy() *VirtualMachineTypeStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineTypeStatus)
	in.DeepCopyInto(out)
	return out
}
