load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "common",
    srcs = [
        "config.go",
        "db_common.go",
    ],
    importpath = "gke-internal.googlesource.com/private-cloud/pkg/apis/public/dbs/postgres/common",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/apis/public/dbs/omnicore/core/v1:core",
        "//vendor/k8s.io/api/core/v1:core",
    ],
)
