// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	omnicorecorev1 "gke-internal.googlesource.com/private-cloud/pkg/apis/public/dbs/omnicore/core/v1"
	corev1 "k8s.io/api/core/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBInstanceSpec) DeepCopyInto(out *DBInstanceSpec) {
	*out = *in
	if in.DBClusterParent != nil {
		in, out := &in.DBClusterParent, &out.DBClusterParent
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(omnicorecorev1.Resource)
		(*in).DeepCopyInto(*out)
	}
	if in.IsStopped != nil {
		in, out := &in.IsStopped, &out.IsStopped
		*out = new(bool)
		**out = **in
	}
	out.ProgressTimeout = in.ProgressTimeout
	if in.LogReplicationSlot != nil {
		in, out := &in.LogReplicationSlot, &out.LogReplicationSlot
		*out = new(bool)
		**out = **in
	}
	if in.SchedulingConfig != nil {
		in, out := &in.SchedulingConfig, &out.SchedulingConfig
		*out = new(omnicorecorev1.SchedulingConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBInstanceSpec.
func (in *DBInstanceSpec) DeepCopy() *DBInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(DBInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBInstanceStatus) DeepCopyInto(out *DBInstanceStatus) {
	*out = *in
	in.EntityStatus.DeepCopyInto(&out.EntityStatus)
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]omnicorecorev1.Endpoint, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBInstanceStatus.
func (in *DBInstanceStatus) DeepCopy() *DBInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(DBInstanceStatus)
	in.DeepCopyInto(out)
	return out
}
