load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")
load("//build/rules/controller_gen:aspect.bzl", "kubebuilder_analyze")
load("//build/rules/controller_gen:kubebuilder.bzl", "api_package")

# gazelle:exclude zz_generated.*.go

kubebuilder_analyze(
    name = "v1alpha2_typedata",
    srcs = [
        "doc.go",
        "groupversion_info.go",
        "harbor_instance.go",
        "harbor_instance_project_types.go",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/apis/public",
        "//vendor/k8s.io/api/core/v1:core",
        "//vendor/k8s.io/api/rbac/v1:rbac",
        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
        "//vendor/k8s.io/apimachinery/pkg/runtime/schema",
        "//vendor/sigs.k8s.io/controller-runtime/pkg/scheme",
    ],
)

api_package(
    name = "v1alpha2_api",
    targets = [":v1alpha2_typedata"],
)

go_library(
    name = "v1alpha2",
    srcs = [
        "annotations.go",
        "doc.go",
        "generated.deepcopy.go",  # keep
        "groupversion_info.go",
        "harbor_instance.go",
        "harbor_instance_conversion.go",
        "harbor_instance_project_conversion.go",
        "harbor_instance_project_types.go",
    ],
    importpath = "gke-internal.googlesource.com/private-cloud/pkg/apis/public/artifactregistry/v1alpha2",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/apis/public",
        "//pkg/apis/public/artifactregistry/v1",
        "//vendor/k8s.io/api/core/v1:core",
        "//vendor/k8s.io/api/rbac/v1:rbac",
        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
        "//vendor/k8s.io/apimachinery/pkg/runtime",  # keep
        "//vendor/k8s.io/apimachinery/pkg/runtime/schema",
        "//vendor/sigs.k8s.io/controller-runtime/pkg/conversion",
        "//vendor/sigs.k8s.io/controller-runtime/pkg/scheme",
    ],
)

go_test(
    name = "v1alpha2_test",
    srcs = [
        "harbor_instance_conversion_test.go",
        "harbor_instance_project_conversion_test.go",
    ],
    embed = [":v1alpha2"],
    deps = [
        "//pkg/apis/public/artifactregistry/v1",
        "//vendor/github.com/google/go-cmp/cmp",
        "//vendor/k8s.io/api/core/v1:core",
        "//vendor/k8s.io/api/rbac/v1:rbac",
        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
    ],
)
