load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "security",
    srcs = ["constants.go"],
    importpath = "github.com/googlecloudplatform/google-distributed-cloud-apis/pkg/apis/public/security",
    visibility = ["//visibility:public"],
    deps = ["//pkg/apis/public"],
)
