// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileShareSource) DeepCopyInto(out *FileShareSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileShareSource.
func (in *FileShareSource) DeepCopy() *FileShareSource {
	if in == nil {
		return nil
	}
	out := new(FileShareSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalVolume) DeepCopyInto(out *LocalVolume) {
	*out = *in
	if in.VolumeMode != nil {
		in, out := &in.VolumeMode, &out.VolumeMode
		*out = new(corev1.PersistentVolumeMode)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalVolume.
func (in *LocalVolume) DeepCopy() *LocalVolume {
	if in == nil {
		return nil
	}
	out := new(LocalVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCVolumeDestination) DeepCopyInto(out *PVCVolumeDestination) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCVolumeDestination.
func (in *PVCVolumeDestination) DeepCopy() *PVCVolumeDestination {
	if in == nil {
		return nil
	}
	out := new(PVCVolumeDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCVolumeSource) DeepCopyInto(out *PVCVolumeSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCVolumeSource.
func (in *PVCVolumeSource) DeepCopy() *PVCVolumeSource {
	if in == nil {
		return nil
	}
	out := new(PVCVolumeSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineDiskVolumeSource) DeepCopyInto(out *VirtualMachineDiskVolumeSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineDiskVolumeSource.
func (in *VirtualMachineDiskVolumeSource) DeepCopy() *VirtualMachineDiskVolumeSource {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineDiskVolumeSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeReplicationDestination) DeepCopyInto(out *VolumeReplicationDestination) {
	*out = *in
	if in.PVC != nil {
		in, out := &in.PVC, &out.PVC
		*out = new(PVCVolumeDestination)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeReplicationDestination.
func (in *VolumeReplicationDestination) DeepCopy() *VolumeReplicationDestination {
	if in == nil {
		return nil
	}
	out := new(VolumeReplicationDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeReplicationRelationship) DeepCopyInto(out *VolumeReplicationRelationship) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeReplicationRelationship.
func (in *VolumeReplicationRelationship) DeepCopy() *VolumeReplicationRelationship {
	if in == nil {
		return nil
	}
	out := new(VolumeReplicationRelationship)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VolumeReplicationRelationship) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeReplicationRelationshipList) DeepCopyInto(out *VolumeReplicationRelationshipList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VolumeReplicationRelationship, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeReplicationRelationshipList.
func (in *VolumeReplicationRelationshipList) DeepCopy() *VolumeReplicationRelationshipList {
	if in == nil {
		return nil
	}
	out := new(VolumeReplicationRelationshipList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VolumeReplicationRelationshipList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeReplicationRelationshipReplica) DeepCopyInto(out *VolumeReplicationRelationshipReplica) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeReplicationRelationshipReplica.
func (in *VolumeReplicationRelationshipReplica) DeepCopy() *VolumeReplicationRelationshipReplica {
	if in == nil {
		return nil
	}
	out := new(VolumeReplicationRelationshipReplica)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VolumeReplicationRelationshipReplica) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeReplicationRelationshipReplicaList) DeepCopyInto(out *VolumeReplicationRelationshipReplicaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VolumeReplicationRelationshipReplica, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeReplicationRelationshipReplicaList.
func (in *VolumeReplicationRelationshipReplicaList) DeepCopy() *VolumeReplicationRelationshipReplicaList {
	if in == nil {
		return nil
	}
	out := new(VolumeReplicationRelationshipReplicaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VolumeReplicationRelationshipReplicaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeReplicationRelationshipReplicaStatus) DeepCopyInto(out *VolumeReplicationRelationshipReplicaStatus) {
	*out = *in
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(VolumeReplicationState)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.ReplicationID != nil {
		in, out := &in.ReplicationID, &out.ReplicationID
		*out = (*in).DeepCopy()
	}
	if in.SourceVolume != nil {
		in, out := &in.SourceVolume, &out.SourceVolume
		*out = new(LocalVolume)
		(*in).DeepCopyInto(*out)
	}
	if in.DestinationVolume != nil {
		in, out := &in.DestinationVolume, &out.DestinationVolume
		*out = new(LocalVolume)
		(*in).DeepCopyInto(*out)
	}
	if in.LagTime != nil {
		in, out := &in.LagTime, &out.LagTime
		*out = new(string)
		**out = **in
	}
	if in.ExportedSnapshotName != nil {
		in, out := &in.ExportedSnapshotName, &out.ExportedSnapshotName
		*out = new(string)
		**out = **in
	}
	if in.LastTransferType != nil {
		in, out := &in.LastTransferType, &out.LastTransferType
		*out = new(string)
		**out = **in
	}
	if in.LastTransferTime != nil {
		in, out := &in.LastTransferTime, &out.LastTransferTime
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeReplicationRelationshipReplicaStatus.
func (in *VolumeReplicationRelationshipReplicaStatus) DeepCopy() *VolumeReplicationRelationshipReplicaStatus {
	if in == nil {
		return nil
	}
	out := new(VolumeReplicationRelationshipReplicaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeReplicationRelationshipSpec) DeepCopyInto(out *VolumeReplicationRelationshipSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	in.Destination.DeepCopyInto(&out.Destination)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeReplicationRelationshipSpec.
func (in *VolumeReplicationRelationshipSpec) DeepCopy() *VolumeReplicationRelationshipSpec {
	if in == nil {
		return nil
	}
	out := new(VolumeReplicationRelationshipSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeReplicationRelationshipStatus) DeepCopyInto(out *VolumeReplicationRelationshipStatus) {
	*out = *in
	in.MuxStatus.DeepCopyInto(&out.MuxStatus)
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]VolumeReplicationRelationshipZoneStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeReplicationRelationshipStatus.
func (in *VolumeReplicationRelationshipStatus) DeepCopy() *VolumeReplicationRelationshipStatus {
	if in == nil {
		return nil
	}
	out := new(VolumeReplicationRelationshipStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeReplicationRelationshipZoneStatus) DeepCopyInto(out *VolumeReplicationRelationshipZoneStatus) {
	*out = *in
	in.ZoneStatus.DeepCopyInto(&out.ZoneStatus)
	in.ReplicaStatus.DeepCopyInto(&out.ReplicaStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeReplicationRelationshipZoneStatus.
func (in *VolumeReplicationRelationshipZoneStatus) DeepCopy() *VolumeReplicationRelationshipZoneStatus {
	if in == nil {
		return nil
	}
	out := new(VolumeReplicationRelationshipZoneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeReplicationSource) DeepCopyInto(out *VolumeReplicationSource) {
	*out = *in
	if in.PVC != nil {
		in, out := &in.PVC, &out.PVC
		*out = new(PVCVolumeSource)
		**out = **in
	}
	if in.VirtualMachineDisk != nil {
		in, out := &in.VirtualMachineDisk, &out.VirtualMachineDisk
		*out = new(VirtualMachineDiskVolumeSource)
		**out = **in
	}
	if in.FileShare != nil {
		in, out := &in.FileShare, &out.FileShare
		*out = new(FileShareSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeReplicationSource.
func (in *VolumeReplicationSource) DeepCopy() *VolumeReplicationSource {
	if in == nil {
		return nil
	}
	out := new(VolumeReplicationSource)
	in.DeepCopyInto(out)
	return out
}
