load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("//build/rules/controller_gen:aspect.bzl", "kubebuilder_analyze")
load("//build/rules/controller_gen:kubebuilder.bzl", "api_package")

# gazelle:exclude zz_generated.*.go

kubebuilder_analyze(
    name = "v1_typedata",
    srcs = [
        "condition_types.go",
        "groupversion_info.go",
        "monitoringrule_types.go",
        "monitoringtarget_types.go",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/apis/core/v1alpha1",
        "//pkg/apis/public",
        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
        "//vendor/k8s.io/apimachinery/pkg/runtime/schema",
        "//vendor/sigs.k8s.io/controller-runtime/pkg/scheme",
    ],
)

kubebuilder_analyze(
    name = "monitoringtarget_v1_typedata",
    srcs = [
        "condition_types.go",
        "groupversion_info.go",
        "monitoringtarget_types.go",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/apis/core/v1alpha1",
        "//pkg/apis/public",
        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
        "//vendor/k8s.io/apimachinery/pkg/runtime/schema",
        "//vendor/sigs.k8s.io/controller-runtime/pkg/scheme",
    ],
)

api_package(
    name = "v1_api",
    targets = [":v1_typedata"],
    visibility = ["//visibility:public"],
)

go_library(
    name = "v1",
    srcs = [
        "condition_types.go",
        "doc.go",
        "generated.deepcopy.go",  # keep
        "groupversion_info.go",
        "monitoringrule_conversion.go",
        "monitoringrule_types.go",
        "monitoringtarget_conversion.go",
        "monitoringtarget_types.go",
    ],
    importpath = "github.com/googlecloudplatform/google-distributed-cloud-apis/pkg/apis/public/monitoring/v1",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/apis/core/v1alpha1",
        "//pkg/apis/public",
        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
        "//vendor/k8s.io/apimachinery/pkg/runtime",  # keep
        "//vendor/k8s.io/apimachinery/pkg/runtime/schema",
        "//vendor/sigs.k8s.io/controller-runtime/pkg/conversion",
        "//vendor/sigs.k8s.io/controller-runtime/pkg/scheme",
    ],
)
