load("@aspect_bazel_lib//lib:write_source_files.bzl", "write_source_files")
load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("//build/rules/controller_gen:aspect.bzl", "kubebuilder_analyze")
load("//build/rules/controller_gen:kubebuilder.bzl", "deepcopygen")

# gazelle:exclude zz_generated.*.go

kubebuilder_analyze(
    name = "replication_typedata",
    srcs = ["replication.go"],
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/apis/public/dbs/omnicore/core/v1:core",
        "//vendor/k8s.io/api/core/v1:core",
        "//vendor/k8s.io/apimachinery/pkg/runtime",
        "//vendor/sigs.k8s.io/controller-runtime/pkg/client",
    ],
)

deepcopygen(
    name = "replication_deepcopy",
    targets = [":replication_typedata"],
    visibility = ["//visibility:public"],
)

write_source_files(
    name = "replication_deepcopy_copy",
    files = {
        "zz_generated.deepcopy.go": ":replication_deepcopy",
    },
)

go_library(
    name = "replication",
    srcs = [
        "replication.go",
        "zz_generated.deepcopy.go",  # keep
    ],
    importpath = "github.com/googlecloudplatform/google-distributed-cloud-apis/pkg/apis/public/dbs/enterprise/replication/v1",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/apis/public/dbs/omnicore/core/v1:core",
        "//vendor/k8s.io/api/core/v1:core",
        "//vendor/k8s.io/apimachinery/pkg/runtime",  # keep
        "//vendor/sigs.k8s.io/controller-runtime/pkg/client",
    ],
)
