// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"

	occoreapi "github.com/googlecloudplatform/google-distributed-cloud-apis/pkg/apis/public/dbs/omnicore/core/v1"
)

const (
	ReplicationDBCLabel = "replication-dbc"
)

type ReplicationControl string

const (
	ReplicationControlSetup   = "setup"
	ReplicationControlPromote = "promote"
	ReplicationControlRewind  = "rewind"

	ReplicationConditionReady   = occoreapi.RCConditionReady
	ReplicationConditionHealthy = occoreapi.RCConditionHealthy

	ReplicationConditionReasonPromoted            = "promoted"
	ReplicationConditionReasonDisableHAInProgress = "disableHAInProgress"
)

// +kubebuilder:object:generate=true

// ReplicationSpec defines the desired state of Replication.
type ReplicationSpec struct {
	// DBCluster is the DBCluster this Replication belongs to.
	DBCluster *corev1.LocalObjectReference `json:"dbcluster,omitempty"`

	// Upstream contains spec for replication upstream database.
	Upstream *UpstreamReplicationSpec `json:"upstream,omitempty"`

	// Downstream contains spec for replication downstream database.
	Downstream *DownstreamReplicationSpec `json:"downstream,omitempty"`
}

// +kubebuilder:object:generate=true

// ReplicationSpec defines the observed state of Replication.
type ReplicationStatus struct {
	occoreapi.EntityStatus `json:",inline"`

	// Upstream contains observed state of replication upstream database.
	Upstream *UpstreamReplicationStatus `json:"upstream,omitempty"`

	// Downstream contains observed state of replication downstream database.
	Downstream *DownstreamReplicationStatus `json:"downstream,omitempty"`
}

// +kubebuilder:object:generate=true

// UpstreamReplicationSpec defines desired spec for replication upstream database.
type UpstreamReplicationSpec struct {
	// Username is the name of the replication user to be used for replication.
	// If not provided, a username will be generated and shown in status.
	// +kubebuilder:validation:Optional
	Username string `json:"username,omitempty"`

	// Password is the reference to the secret storing replication user password.
	// If not provided, a password will be generated and stored in a secret shown in status.
	// +kubebuilder:validation:Optional
	Password *corev1.SecretReference `json:"password,omitempty"`

	// ReplicationSlotName is the name of the replication slot to be used for replication.
	// If not provided, a replication slot name will be generated and shown in status.
	// +kubebuilder:validation:Optional
	ReplicationSlotName string `json:"replicationSlotName,omitempty"`

	// Synchronous specifies whether the replication slot should be configured for synchronous replication.
	// If true, the applicationName will be added to the list of synchronous standbys. Note: This will have
	// a negative impact on performance.
	// +kubebuilder:validation:Enum="true";"false"
	// +kubebuilder:default="false"
	Synchronous string `json:"synchronous,omitempty"`

	// ApplicationName is the identifier of the synchronous replication connection. This value is required if
	// Synchronous is set to "true".
	// +kubebuilder:validation:Optional
	ApplicationName string `json:"applicationName"`

	// LogicalReplication specifies the logical replication configuration for the replication slot.
	// If empty, the replication slot will be configured as a physical replication slot.
	// +kubebuilder:validation:Optional
	LogicalReplication *UpstreamLogicalReplicationSpec `json:"logicalReplication,omitempty"`

	// LogReplicationSlot if set to true will allow this replication slot to be
	// written to WAL files generated by the primary instance.
	//
	// It is recommended to have this option enabled especially in cross-region
	// replications. Make sure that the primary DBCluster has the
	// ReplayReplicationSlotsOnStandbys options enabled as well to ensure the
	// replication slot written to WAL files will be replayed on the HA
	// standbys.
	//
	// By having both options enabled you will ensure that in the event of an HA
	// failover or switchover on the primary DBCluster, the new HA primary
	// instance retains WAL files which have not yet been received by the
	// secondary DBCluster.
	//
	// Note, modifying this field will cause the primary database to restart.
	//
	// nullon(dbs-fleet)
	LogReplicationSlot *bool `json:"logReplicationSlot,omitempty"`
}

// +kubebuilder:object:generate=true

// DownstreamReplicationSpec defines desired spec for replication downstream database.
type DownstreamReplicationSpec struct {
	// Host is the upstream database's connection endpoint that this database
	// can access for replication.
	// +kubebuilder:validation:Required
	Host string `json:"host"`

	// Port is the upstream database's port that this database can access
	// for replication. Default is 5432.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=65535
	// +kubebuilder:default:5432
	Port int32 `json:"port,omitempty"`

	// Username is the name of the replication user created on the upstream database,
	// and will be used by this database to connect to upstream for replication.
	// +kubebuilder:validation:Required
	Username string `json:"username"`

	// Password is the reference to the secret storing upstream database's replication user password.
	// +kubebuilder:validation:Required
	Password *corev1.SecretReference `json:"password"`

	// ReplicationSlotName is the name of the replication slot created on the
	// upstream database, and will be used by this database for replication.
	// +kubebuilder:validation:Required
	ReplicationSlotName string `json:"replicationSlotName"`

	// Control specifies the replication operation to be taken on this database.
	// This field is required, and the allowed values are setup, promote, and rewind.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Enum=setup;promote;rewind
	Control string `json:"control"`
}

// +kubebuilder:object:generate=true

type UpstreamLogicalReplicationSpec struct {
	// PluginName is the decoding plugin associated with this slot.
	// See https://www.postgresql.org/docs/current/logicaldecoding-explanation.html#LOGICALDECODING-EXPLANATION-OUTPUT-PLUGINS for details.
	// +kubebuilder:validation:Required
	PluginName string `json:"pluginName"`

	// DatabaseName is the database associated with this slot. Only changes from this database
	// will be streamed through the slot.
	// +kubebuilder:validation:Required
	DatabaseName string `json:"databaseName"`
}

// +kubebuilder:object:generate=true
// UpstreamReplicationStatus defines the observed state of replication upstream database.
type UpstreamReplicationStatus struct {
	// Host is this database's connection endpoint that downstream databases
	// can access for replication.
	// +kubebuilder:validation:Optional
	Host string `json:"host"`

	// Port is this database's port that downstream databases can access
	// for replication.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=65535
	Port int32 `json:"port,omitempty"`

	// Username is the name of the replication user on this database.
	// Downstream databases can use this user to connect to this database for replication.
	// +kubebuilder:validation:Optional
	Username string `json:"username"`

	// Password is the reference to the secret storing this database's replication user password.
	// +kubebuilder:validation:Optional
	Password *corev1.SecretReference `json:"password"`

	// ReplicationSlotName is the name of the replication slot created on this database.
	// Downstream databases can use this replication slot for replication.
	// +kubebuilder:validation:Optional
	ReplicationSlotName string `json:"replicationSlotName"`
}

// +kubebuilder:object:generate=true

// DownstreamReplicationStatus defines the observed state of replication downstream database.
type DownstreamReplicationStatus struct {
	PhysicalDownstream *occoreapi.ReplicationPhysicalDownstreamStatus `json:"physicalDownstream,omitempty"`
}

// Replication contains user facing replication configuration of a database.
type Replication interface {
	occoreapi.Entity
	ReplicationSpec() *ReplicationSpec
	ReplicationStatus() *ReplicationStatus
}

// ReplicationList is a common interface for all the ReplicationList implementations
type ReplicationList interface {
	client.ObjectList
	Replications() []Replication
}

func IsLogicalReplication(rep Replication) bool {
	upstream := rep.ReplicationSpec().Upstream
	return upstream != nil && upstream.LogicalReplication != nil
}
