// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	omnicorecorev1 "github.com/googlecloudplatform/google-distributed-cloud-apis/pkg/apis/public/dbs/omnicore/core/v1"
	corev1 "k8s.io/api/core/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownstreamReplicationSpec) DeepCopyInto(out *DownstreamReplicationSpec) {
	*out = *in
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(corev1.SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownstreamReplicationSpec.
func (in *DownstreamReplicationSpec) DeepCopy() *DownstreamReplicationSpec {
	if in == nil {
		return nil
	}
	out := new(DownstreamReplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownstreamReplicationStatus) DeepCopyInto(out *DownstreamReplicationStatus) {
	*out = *in
	if in.PhysicalDownstream != nil {
		in, out := &in.PhysicalDownstream, &out.PhysicalDownstream
		*out = new(omnicorecorev1.ReplicationPhysicalDownstreamStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownstreamReplicationStatus.
func (in *DownstreamReplicationStatus) DeepCopy() *DownstreamReplicationStatus {
	if in == nil {
		return nil
	}
	out := new(DownstreamReplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationSpec) DeepCopyInto(out *ReplicationSpec) {
	*out = *in
	if in.DBCluster != nil {
		in, out := &in.DBCluster, &out.DBCluster
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.Upstream != nil {
		in, out := &in.Upstream, &out.Upstream
		*out = new(UpstreamReplicationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Downstream != nil {
		in, out := &in.Downstream, &out.Downstream
		*out = new(DownstreamReplicationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationSpec.
func (in *ReplicationSpec) DeepCopy() *ReplicationSpec {
	if in == nil {
		return nil
	}
	out := new(ReplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationStatus) DeepCopyInto(out *ReplicationStatus) {
	*out = *in
	in.EntityStatus.DeepCopyInto(&out.EntityStatus)
	if in.Upstream != nil {
		in, out := &in.Upstream, &out.Upstream
		*out = new(UpstreamReplicationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Downstream != nil {
		in, out := &in.Downstream, &out.Downstream
		*out = new(DownstreamReplicationStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationStatus.
func (in *ReplicationStatus) DeepCopy() *ReplicationStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamLogicalReplicationSpec) DeepCopyInto(out *UpstreamLogicalReplicationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamLogicalReplicationSpec.
func (in *UpstreamLogicalReplicationSpec) DeepCopy() *UpstreamLogicalReplicationSpec {
	if in == nil {
		return nil
	}
	out := new(UpstreamLogicalReplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamReplicationSpec) DeepCopyInto(out *UpstreamReplicationSpec) {
	*out = *in
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(corev1.SecretReference)
		**out = **in
	}
	if in.LogicalReplication != nil {
		in, out := &in.LogicalReplication, &out.LogicalReplication
		*out = new(UpstreamLogicalReplicationSpec)
		**out = **in
	}
	if in.LogReplicationSlot != nil {
		in, out := &in.LogReplicationSlot, &out.LogReplicationSlot
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamReplicationSpec.
func (in *UpstreamReplicationSpec) DeepCopy() *UpstreamReplicationSpec {
	if in == nil {
		return nil
	}
	out := new(UpstreamReplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamReplicationStatus) DeepCopyInto(out *UpstreamReplicationStatus) {
	*out = *in
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(corev1.SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamReplicationStatus.
func (in *UpstreamReplicationStatus) DeepCopy() *UpstreamReplicationStatus {
	if in == nil {
		return nil
	}
	out := new(UpstreamReplicationStatus)
	in.DeepCopyInto(out)
	return out
}
